### ISSUE TITLE
Icons shown as question marks after mojave update

### ISSUE THREAD

**Issue by mert-kosova** [bhilburn/powerlevel9k#1001]
Hello, I hope this worths an issue but I just started having this problem after mac osx mojave update. Before that everything was working as expected. After mojave update I lost my icons on my terminal. I'm using V1rgul's configuration with iTerm2. Currently using Meslo LG Regular for Powerline font when I run `get_icon_names` command on shell I get most icons as question marks. Might be an easy fix but I wanted to open an issue because more people might be having this issue and there aren't many results showing up because update is new.

- zsh version: 5.3
- zsh framework: oh-my-zsh
- emulator: iTerm2 recently updated via brew
not sure about how I installed p9k or current version.

- font: Meslo LG M for Powerline
- font config: awesome-fontconfig
-output of `get_icon_names`: mostly question marks.

**Comment by stayko16** [comment]
I repeated the steps from the guide here and it worked from me:
[https://github.com/gabrielelana/awesome-terminal-fonts/wiki/OS-X](https://github.com/gabrielelana/awesome-terminal-fonts/wiki/OS-X)

**Comment by onaforeignshore** [comment]
After every update, the plist gets reset

**Comment by mert-kosova** [comment]
Thank you @stayko16 @onaforeignshore, I wasn't aware that plist resets between updates.

**Comment by FedericoCapaldo** [comment]
Bumped into this issue and posting here what solved it for me: 
[https://github.com/Powerlevel9k/powerlevel9k/wiki/Install-Instructions#step-2-install-a-powerline-font](https://github.com/Powerlevel9k/powerlevel9k/wiki/Install-Instructions#step-2-install-a-powerline-font) on this link follow "Option 1: Install Powerline Fonts". 

The instructions are very brief so here following is what it entailed for me to follow the above link

### Step 1

There is an external link in this explanation  "Option 1: Install Powerline Fonts".  This points to the actual installatiion of the fonts: 

[https://powerline.readthedocs.io/en/latest/installation/linux.html#fonts-installation](https://powerline.readthedocs.io/en/latest/installation/linux.html#fonts-installation). On this link I folowed the first 4 steps.

To follow these 4 steps, the process also required me to install fontconfig in order to use the `fc-cache` command.
`brew install fontconfig`

Please note that the paths on your system for `~/.local/share/fonts/` in step 2 and `~/.config/fontconfig/conf.d/` in step 4 may be different. Google around to find those paths for you.

For me they were respecively: `/Library/Fonts` and `/usr/local/etc/fonts/conf.d`

### Step 2
Restart iterm2 and in the settings **Preferences > Profile > Text > Use a different Font for non-ASCII text > Select from dropdown "powerlineSymbols"**

Really hope that someone else will use these instruction and won't have to struggle as much as I did to get fix the questions marks on their iterm. Peace.
