### ISSUE TITLE
Allow truncate_with_folder_marker to use multiple markers

### ISSUE THREAD

**Issue by fishpen0** [bhilburn/powerlevel9k#1039]
Currently I use the `truncate_with_folder_marker` truncation strategy for my shell, however this leaves me only able to truncate by one kind of marker.  Right now I set `POWERLEVEL9K_SHORTEN_FOLDER_MARKER=.git` to truncate to the closest parent git directory.  However this means I am unable to truncate to other vcs systems or other project strutcures.

I would like to be able to provide multiple markers. For example, if I set `POWERLEVEL9K_SHORTEN_FOLDER_MARKER=".git .hg .terraform"` I would like it to find the closest parent directory that is a git repo, a mercurial repo, or a terraform project and truncate to that.

**Comment by dritter** [comment]
Hi @fishpen0 . Thanks for your feature request. This will be indeed possible in the upcoming Version.
You can use this, if you update to the `next` branch, our development branch.
To find multiple markers, you'll need to set `P9K_DIR_SHORTEN_DELIMITER=(.git|.hg|.terraform)`. Syntax is like that, because we use zsh's globbing mechanism here.
