### ISSUE TITLE
command not found: vcs_info

### ISSUE THREAD

**Issue by mett96** [bhilburn/powerlevel9k#1116]
I put **vcs** into my POWERLEVEL9K_LEFT_PROMPT_ELEMENTS. 
But when I reload the terminal, it is shown a message:

**prompt_vcs:6: command not found: vcs_info**

What is the problem with git?

My environment:
- zsh 5.6.2 (x86_64-apple-darwin18.2.0)
- I use Oh-My-ZSH
- I installed P9K with home-brew 

Thanks in advice

**Comment by mett96** [comment]
Now work!
thank you very much!!!

**Comment by dritter** [comment]
Glad you got it working @mett96 . Thanks for the support @Syphdias .

**Comment by martmists** [comment]
I'm getting the same issue (using oh-my-zsh), but it's sourced AFTER defining all PL9K variables.

**Comment by Syphdias** [comment]
Hi @martmists, can you provide more information about your setup?  
zsh version, which P9K branch/commit do you use, relevant variables from your `zshrc`...

**Comment by martmists** [comment]
Latest zsh from Arch Repos, latest oh-my-zsh from git, installed using the `oh-my-zsh` method just now.

zshrc: [link](https://transfer.sh/UU3pN/.zshrc)

**Comment by Syphdias** [comment]
Looks to me like the `_joined` in `vcs_joined` breaks it for some reason but only on the `master` branch. Maybe because it is used after `newline`? Additionally `_joined` does nothing after `newline` as far as I understand it.
@martmists Your solution: Replace `vcs_joined` with `vcs`

Also: the alias for the command `pyenv` breaks the segment.
@dritter Is this something that should be fixed? Possibly a problem of all external program calls.

**Comment by martmists** [comment]
The odd thing is that this exact same zshrc works like this locally: 
![image](https://user-images.githubusercontent.com/16361449/49897641-05ef9f80-fe57-11e8-9f24-175bfa3edf3a.png)

But on the remote server: 
![image](https://user-images.githubusercontent.com/16361449/49897674-16077f00-fe57-11e8-885c-af6cf06475ba.png)

**Comment by dritter** [comment]
The problem is indeed joining the vcs segment. And after a newline, that is useless anyway. So the workaround is to remove the `_joined` as @Syphdias suggested.
Technically speaking the problem occurs because of us loading VCS_INFO only if the `vcs` segment is in use. But these lines do not work with joined segments. This is usually no problem, but here it is.
Troubling lines:
```zsh
  if segment_in_use "vcs"; then
    powerlevel9k_vcs_init
  fi
```

@Syphdias I won't consider this an edge case; nobody (except you @martmists ) seems to use a joined VCS segment. But I won't decline a bugfix for it either. ;)
