### ISSUE TITLE
Unknown character in history.p9k?

### ISSUE THREAD

**Issue by cin** [bhilburn/powerlevel9k#1117]
I just switched over from master to next and it appears the [history.p9k](https://github.com/bhilburn/powerlevel9k/blob/next/segments/history.p9k#L15) file is referencing a character not present in the `awesome-fontconfig`. If I `echo "\uE29B"`, I get a question mark. For now, I just made them blank. I'm using `P9K_MODE='awesome-fontconfig'`. What is this supposed to render? Should I be using a different font? TIA!

**Comment by dritter** [comment]
Ha. Good catch @cin !
In `master` there was no icon for that.. It looks like [there is one](https://github.com/gabrielelana/awesome-terminal-fonts/blob/9be0f571753dcdedfb6181f54686bca97cc3e7f8/build/fontawesome-regular.sh#L358) in `awesome-fontconfig-mapped` mode. It may be `$'\uF1DA'` in `awesome-fontconfig` mode (if `$'\uE29A '` from `history.p9k` does not work). But I am guessing here, without a proper fontconfig setup. It would be awesome, if you could:
- verify the code points. It should render like in NerdFonts:
 ![](https://user-images.githubusercontent.com/1544760/49756627-aceb0480-fcba-11e8-8ecb-6b9dfe3f34e2.png)
- create a PR, if you found no suitable icon

Thanks

**Comment by cin** [comment]
Thanks @dritter I would have never found that. It definitely does not look like NerdFonts though. Here's an example: 
![image](https://user-images.githubusercontent.com/26170/49758921-30dac780-fc8e-11e8-886c-770eb127b308.png)
I'll take a look around and see if I can find a suitable replacement.

**Comment by dritter** [comment]
I think I explained myself wrong: There is no such thing as _the_ history icon (unlike for other segments, where we render a logo of a company/project). So we have so find an arbitrary icon that represents "history".
IMHO `$'\uF1DA'` is a good choice, because the segment allows to execute a past command again (with `!<history_id>`; example `!2`, if `2` is the number the history segment shows). I rather find `$'\uE29A '` odd. Looks too much like a checklist to me.. WDYT?

**Comment by cin** [comment]
Sorry for the delay. I agree. I think `$'\uF1DA` is a good choice as well. 👍

**Comment by dritter** [comment]
Cool. Thanks for your feedback. Do you mind create a PR for that?

**Comment by dritter** [comment]
Fixed with #1129
