### ISSUE TITLE
Terminal printing lots of "Operation not permitted" errors regarding certain directories.

### ISSUE THREAD

**Issue by Nobody912** [bhilburn/powerlevel9k#1134]
#### Describe Your Issue
Terminal Prints:
> warning: could not open directory 'Library/[Insert Directories]': Operation not permitted

[See it in action:](https://gyazo.com/8e2d3018a5dfb7a89a2a694b2bcb56f3)

#### Have you tried to debug or fix it?
Reinstalled ZSH, Oh-My-ZSH, and PowerLevel9k multiple times. Not sure of what caused the error, I'm relatively new to all of this.

#### Environment Information
OS: **macOS 10.14.2 (18C54)**
System: **MacBook Pro (Retina, 13-inch, Early 2015)**
ZSH Version: **zsh 5.6.2 (x86_64-apple-darwin18.2.0)**
ZSH Framework: **Oh-My-ZSH**
Installation Method: **Repo**
P9K Version: **Release v0.6.6 (Not sure, probably latest)**
Terminal Emulator: **iTerm2**

**Comment by Nobody912** [comment]
#### **echo $GIT_DIR**
`echo $GIT_DIR` only indents a line. 

#### **Dotfiles**
[https://imgur.com/a/r7HRxB2](https://imgur.com/a/r7HRxB2)

#### **~/.zshrc**
[https://pastebin.com/jAPJu37x](https://pastebin.com/jAPJu37x)

**Comment by dritter** [comment]
Okay. `GIT_DIR` is not set. But it is still a Git Checkout. My best guess is that you have some symlinks lying around in your `Library` Folder. That symlinks seem to point somewhere you don't have access to.
Could you try to put the `Library` Folder in your `.gitignore`?

**Comment by Nobody912** [comment]
Tried and put ```Library``` in the .gitignore. fixed the issue but now terminal load time is ungodly slow. I have some debugging work to do.

**Comment by dritter** [comment]
@88maomao Well. Maybe. I would ask why there is a file/folder you don't have access to in your repo.

@Nobody912 You could have a look at our [measurings](https://github.com/bhilburn/powerlevel9k/pull/1046#issuecomment-435549640) [we](https://github.com/bhilburn/powerlevel9k/issues/1105#issuecomment-443549388) [did](https://github.com/bhilburn/powerlevel9k/issues/1054#issue-377635256). Basically, you could check the commands that are executed in the vcs segment, and see if they are slow itself.
A shot in the dark: Probably that is related to a lot of untracked files (that's what I would guess if my Home-dir would be a repo).
In general, having large repos is usually a bad idea, because there is a lot of overhead (git tracking files, P9K trying to extract the status from git, etc.).

**Comment by 88maomao** [comment]
@dritter And I would answer: during testing anything can happen. In my case it was 'docker run -i -t --rm -v $(pwd)/db:/var/lib/posgresql/data postgresql' inside projects folder.

Btw. about slow performance on a large repo https://github.com/robbyrussell/oh-my-zsh/issues/3009#issuecomment-420763151. Having such a latch improves karma.

**Comment by dritter** [comment]
@88maomao Good answer! I just merged your PR!
