### ISSUE TITLE
Ask me, there are vertical lines. It looks strange. What's the reason?

### ISSUE THREAD

**Issue by MaxBill** [bhilburn/powerlevel9k#1300]
![TIM图片20190606094343](https://user-images.githubusercontent.com/16558525/59001059-c58a4080-883f-11e9-9df5-8b200b90ee58.png)

The picture above is my terminal, with vertical lines.

Seeing how other people's tutorials are configured is like this:
![TIM图片20190606094351](https://user-images.githubusercontent.com/16558525/59001074-dcc92e00-883f-11e9-8c77-b901c886a7ab.png)

Replacement of another terminal also shows a vertical line, what is the reason?

**Comment by romkatv** [comment]
The presence and the size of the gap depends on your font. The arrows you see in your right prompt are made of two symbols: a left-pointing triangle and a space. You can print a blue arrow manually with `print -P '%F{blue}\uE0B2%f%K{blue} %k'`.

![arrow](https://user-images.githubusercontent.com/1282067/59009726-17769a80-882f-11e9-8deb-19f5c0a8d83f.png)

To eliminate the gaps you can either try another font (I'm using [Meslo LG S Regular Nerd Font Complete Mono](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Meslo/S/Regular/complete/Meslo%20LG%20S%20Regular%20Nerd%20Font%20Complete%20Mono.ttf) in the above screenshot) or change the style of your prompt to get rid of the arrows altogether.

I'm personally using the latter approach combined with [Powerlevel10k](https://github.com/romkatv/powerlevel10k/) (it's the same as Powerlevel9k but much faster). By starting with Pure Power instead of the default configuration you'll get a modern, functional and fast prompt rather than being stuck with visual noise. Another advantage is that it works with any font. You can try it like this:

```zsh
git clone https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
( cd && curl -fsSLO https://raw.githubusercontent.com/romkatv/dotfiles-public/master/.purepower )
# This will make your prompt faster without changing its appearance.
echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>! ~/.zshrc
# This will change the appearance of your prompt. You can edit ~/.purepower to customize it further.
echo 'source ~/.purepower' >>! ~/.zshrc
```

**Comment by MaxBill** [comment]
Thank you for answering my questions. Installed Powlevel10k or has a vertical display. I'll try to install the font you said.
