### ISSUE TITLE
battery segment?

### ISSUE THREAD

**Issue by kevinSuttle** [bhilburn/powerlevel9k#168]
Can this theme support a battery status segment?

**Comment by dritter** [comment]
Yep. There is already one in the development branch called [`next`](https://github.com/bhilburn/powerlevel9k/tree/next#battery). ;)

**Comment by kevinSuttle** [comment]
Awesome!

**Comment by kevinSuttle** [comment]
Any idea what the last character is in the battery status?
I tried both Powerline and Awesome fonts, to no avail. 

`POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(time battery)`

<img width="369" alt="screen shot 2015-12-28 at 8 26 55 pm" src="https://cloud.githubusercontent.com/assets/95672/12028203/72796302-ada1-11e5-84c8-f568cc6453cd.png">

**Comment by kevinSuttle** [comment]
Oh. `\u1F50B` :battery:. Duh.

**Comment by kevinSuttle** [comment]
I like the default one for root: :zap: _(aka "high voltage sign")_

**Comment by dritter** [comment]
@kevinSuttle Then, just use it: `POWERLEVEL9K_BATTERY_ICON=$'\u26A1'`. :wink: 
But this is an emoji. If you want to change the color of that icon, you should use `$'\uE801'` (in `awesome-patched` mode). If you use the `awesome-fontconfig` mode, then it is `$'\uF201'`

**Comment by praveenpuglia** [comment]
@dritter , @kevinSuttle - This worked for me. Although I still believe it should just work out of the box instead of the extra setting. :)
Ref : #270

**Comment by dritter** [comment]
@praveenpuglia The "high voltage sign" should be used for superpower-users (like root) for the sake of clarity.

Regarding the out-of-the-box experience: Unfortunately this depends heavily on the users settings. If one uses a different fontconfig-configuration he might get totally different icons.. The root cause for the problem is the use of non-official (private) code points which might represent different icons across different fonts.
I hoped the code points for emoji are more stable, but that seems wrong.. Do you have a code point for a proper battery symbol?

**Comment by praveenpuglia** [comment]
Sounds like a no! :( I ended up copying the glyph altogether and pasting it in my zshrc file. I am currently using this one - 🔌
