### ISSUE TITLE
Regression: POWERLEVEL9K_DIR_FOREGROUND is not working anymore

### ISSUE THREAD

**Issue by JimmyAx** [bhilburn/powerlevel9k#184]
As title says. I've set `POWERLEVEL9K_DIR_FOREGROUND=white` in my config, yet the color is still black. This used to work fine, but the commit cd5b4d0debac05a74131f06efa918172586865ec broke it. Found it using a `git bisect`. It seems to work again if I change `$0_HOME` back to `$0`.

**Comment by bhilburn** [comment]
Paging @dritter.

We have a few other items on `next`, too. Once this gets fixed, I'll make a v0.3.1 patch release.

**Comment by dritter** [comment]
This is not a bug - it's a feature. :smile: I always wanted to say that.

This is due to a change to the `dir` segment. It now distinguishes between being inside the home folder and outside of it. These states have effect on the customization variables for this segment. You have to set the variables like `POWERLEVEL9K_DIR_HOME_FOREGROUND="white"` and `POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="green"`. Note the "state" in the variable name.

I only forgot to mention that change in the `CHANGELOG`. I opened #180 for that.

Other segments that have state are described [here](https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#special-segment-colors).

**Comment by outcoldman** [comment]
:+1:

**Comment by bhilburn** [comment]
@dritter - Perfect! Thank you!
