### ISSUE TITLE
VCS dirty color collision on `next`

### ISSUE THREAD

**Issue by bhilburn** [bhilburn/powerlevel9k#217]
We recently added a third color to the VCS prompt, red, to indicate tracked dirty status.

Unfortunately, in doing so, we created an issue, because our default VCS action format text is also red. I created a test scenario to show the problem:

![oops](https://cloud.githubusercontent.com/assets/569571/13130840/05dec8a4-d59c-11e5-8951-440c5dcd9961.png)

The obvious fix is to simply change the default action format text color. *But*, since making the change to use red to indicate tracked files are dirty, I've decided I'm not a huge fan of this. It's too.... angry, I guess, is the best way to put it. 

So, let's revisit this. We have eight colors to choose from. Does anyone have suggestions for our default color assignments?

Possible colors: black, red, green, yellow, blue, magenta, cyan, white

|State|Background|Foreground|Action Format|
|------|------------|--------------|------------|
|Clean|Green|Black|N/A|
|Half-Dirty|??|Black|??|
|Dirty|??|??|??|

(Remember that users can override the color settings - what we are trying to achieve, here, are defaults that most users will be happy with)

**Comment by dritter** [comment]
Almost all other themes I've seen don't make this decision on a background color level. Most of them use icons for that. But somewhere I've seen that behavior (yellow for `dirty`, red for `untracked`). I just can't find where it was..
So that might be an option to use yellow for both states. In this case we are on a line with other themes and provide an opportunity to change that.

But from a design perspective the stronger color should be used for the stronger state. So from this point of view `untracked` should be yellow and `dirty` should be red. That would be at least a consistent coloring of the segment.

TBH I am not a fan of the untracked state. I always have a ton of files lying around in my repos (quite messy, I know).

**Comment by bhilburn** [comment]
@dritter - I actually like that idea. Keep the color green for untracked files, but indicate with an icon, and then only change the color if the repo is actually dirty.

I'll mull this over a bit more, but I really like that suggestion. So, just to lay it out, this would be what it looks like:

|State|Background|Foreground|Action Format|
|------|------------|--------------|------------|
|Clean|Green|Black|N/A|
|Half-Dirty|Green|Black + Icon Indicator|N/A|
|Dirty|Yellow|Black|Red|

**Comment by dritter** [comment]
Green for both states is an option for us too. :smile: 
Sounds like good solution. :+1:

**Comment by bhilburn** [comment]
Fixed by 4f0c3ff
