### ISSUE TITLE
Context icon not displayed properly

### ISSUE THREAD

**Issue by vinaychandra** [bhilburn/powerlevel9k#231]
As you can see, the font is installed correctly but the prompt is breaking in between. What is the solution for this probelm
![snapshot2](https://cloud.githubusercontent.com/assets/5670927/13630006/e23cf502-e602-11e5-8cc0-a2485ecbab07.png)

**Comment by dritter** [comment]
What do you mean by saying the prompt breaks in between? Do you want a multiline-prompt? If so, you need to set `POWERLEVEL9K_PROMPT_ON_NEWLINE=true`.

**Comment by vinaychandra** [comment]
Sorry for my english. I meant that the icon that is being displayed is broken. In the first line, the home icon is partially displayed. I want to set it right

**Comment by dritter** [comment]
No need to apologize. I was to stupid to see the broken icon in the first place. :smile: 

The problem is quite complex, and has to do with how the terminal editor renders multi-width glyphs. So it is more an issue somewhere there (nothing we can really do about).

A quick solution _could_ be to render more whitespace after the icon.. Set `POWERLEVEL9K_HOME_ICON=$'\UE12C '` (note the whitespace after the codepoint). This codepoint is for `awesome-patched`-mode. If you use `awesome-fontconfig`, it should be `\UF015`.

It might also be a setting in your terminal emulator. Maybe there is somewhere a switch to treat all fonts as monospaced fonts..

Btw. which terminal emulator do you use? Is that terminix?

**Comment by vinaychandra** [comment]
It is Konsole

**Comment by dritter** [comment]
Okay. Good to know. But did giving the icon more whitespace work?

**Comment by vinaychandra** [comment]
Yes. Giving the icon more whitespace worked. Thank you :smiley:

**Comment by 9ao9ai9ar** [comment]
@vinaychandra I patched the problem using this ugly code:
```
for key in ${(k)icons[@]}
do
    if [[ ! $key =~ 'SEPARATOR' ]]
    then
        icons[$key]=" ${icons[$key]} "
    fi
done
```
Add it after `antigen apply` in your `.zshrc`.
