### ISSUE TITLE
precmd:4: command not found: vcs_info_hookadd

### ISSUE THREAD

**Issue by fuzzmz** [bhilburn/powerlevel9k#26]
Tried enabling the theme but I receive the `precmd:4: command not found: vcs_info_hookadd` info in the command line and it seems like it tries to display VCS related info no matter if the current folder is a repository or not.

![error](http://i.imgur.com/FY1ws0O.png)

**Comment by fuzzmz** [comment]
What's strange is that it works ok on my local machine, but doesn't on my VPS with the exact same install and `.zshrc`

**Comment by dritter** [comment]
Hi serban!

Thanks for the info. Yes indeed, we invoke the vcs_info subsystem
regardless of beeing in a repository or not. This is because the vcs_info
checks the folder by itself.

What version oft zsh do you have?

Best regards,
Dominik
Am 17.04.2015 20:00 schrieb "Serban Constantin" <notifications@github.com>:

Tried enabling the theme but I receive the precmd:4: command not found:
vcs_info_hookadd info in the command line and it seems like it tries to
display VCS related info no matter if the current folder is a repository or
not.

[image: error]
<https://camo.githubusercontent.com/463a9d305b4a81ef0781f1fe1592a81eaf45f55b/687474703a2f2f692e696d6775722e636f6d2f4659317773304f2e706e67>

—
Reply to this email directly or view it on GitHub
<https://github.com/bhilburn/powerlevel9k/issues/26>.

**Comment by fuzzmz** [comment]
pebcak. Looks like my distro's package manager was still on version 4.x of zsh. Upgraded to 5.0.7 and now the message is no longer displayed.

**Comment by lylemoffitt** [comment]
As a helpful note to anyone who comes here with this problem, I offer the following.

I use OSX 10.8, with Homebrew as a package manager. I was encountering this problem consistently despite having zsh v5.0.7 as the first of its name in my PATH. I reinstalled everything zsh and still the problem persisted.

The real root of the issue here is that on macs, terminal emulators (Terminal, iTerm, etc.) use the login shell by default. On OSX 10.8, the "Login shell" is defined in a hidden "Advanced Options" panel of the "Users & Groups" preference pane. In order for a shell to be entered there, it must be listed in `/etc/shells` and AFAIK must be in `/bin/` (via a symlink at least). The zsh installation from Homebrew was in neither. 

There are two solutions here. The easy (and safer?) solution is to just change your preferences in whatever terminal emulator you use to start with a specific command, rather than the default. The harder (and more robust?) solution is to change the "Login shell" in System Preferences, symlink `/bin/zsh5` to `/usr/local/bin/zsh`, and edit `/etc/shells`.

Hope this helps the next person to stumble on this problem.

**Comment by bhilburn** [comment]
@lylemoffitt - Thanks so much for leaving this here! This is very helpful. I may incorporate your feedback into the README.
