### ISSUE TITLE
Battery Indicator Icon Doesn't Work

### ISSUE THREAD

**Issue by praveenpuglia** [bhilburn/powerlevel9k#270]
All the other icons work but this one doesn't. :sob: 
![image](https://cloud.githubusercontent.com/assets/313363/15704485/96e33f42-2808-11e6-8a23-c1e9fe698680.png)

**Comment by dritter** [comment]
Do you use `awesome-fontconfig` or `awesome-patched` mode?

A quick solution could be to set `POWERLEVEL9K_BATTERY_ICON` to the icon that works for you.

**Comment by praveenpuglia** [comment]
I use `awesome-fontconfig`.

**Comment by bhilburn** [comment]
Not sure what to make of this - especially if the other code points are working.

How did you install the Awesome-Patched Fonts, @praveenpuglia?

**Comment by dritter** [comment]
It's hard to say why that single icon does not work on your machine. That depends on your fontconfig-configuration. Could you double-check that at least one of your configured fonts offer a good glyph for `\u1F50B`? 
It seems a bit strange, as this sign is an emoji. If your fonts are configured correctly, you should even be able to see this glyph in your browser:🔋 

It might be necessary to install some fonts in order to see the emoji ([Ubuntu example](https://www.kirsle.net/blog/entry/make-emoji-work-in-linux)).

**Comment by praveenpuglia** [comment]
@bhilburn 
I went to this repo and installed the fonts by executing `./install.sh` from the cloned repo. In my `.zshrc` I am using `awesome-fontconfig` as the mode.

@dritter - I do see a battery, filled in green. I am however not sure whether it's just github replacing it or my machine is really rendering it correctly.

How do I check what fonts I have configured and if they support that glyph or not?

**Comment by praveenpuglia** [comment]
Seems like the fontawesome **.ttf** installed using **awesome-terminal-fonts** doesn't even have that battery icon. I checked it with the character map in libre office writer. Then, I downloaded the ttf from [here](https://github.com/FortAwesome/Font-Awesome/blob/master/fonts/fontawesome-webfont.ttf) and it now shows the battery icon in the character map! :disappointed:

**Comment by bhilburn** [comment]
@praveenpuglia - Ah, interesting. It sounds like you are using an alternate version of the font. 

Don't forget to reset the font in your terminal emulator in order to try out the new fonts you are trying out!

I'm going to close this bug as I don't think it's an issue with `powerlevel9k`. Feel free to keep the conversation going, though, @praveenpuglia. It would be good to know which fonts work and which don't.

**Comment by ratijas** [comment]
got same problem with battery icon.  i was using 'awesome-fontconfig' by installing `otf-sauce-code-powerline-git` via AUR.

fixed by installing `noto-fonts-emoji`. 🔋 👍
