### ISSUE TITLE
prompt_dir break if go to .git directory

### ISSUE THREAD

**Issue by kcwu** [bhilburn/powerlevel9k#290]
How to reproduce:
```
git init
cd .git
```
then powerlevel9k break with following message:
```
prompt_dir:27: substring expression: -3 < 0
```

This is because `git rev-parse --git-dir` output `.` for the `.git` directory. And `package_path=${repo_path:0:-4}` failed.

**Comment by bhilburn** [comment]
@kcwu - Hm, I can't reproduce this issue. Can you share your powerlevel9k config? Also, what branch / release are you using?

**Comment by kcwu** [comment]
I found this related to these two lines
```
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_with_package_name
```

**Comment by bhilburn** [comment]
@kcwu - Aha, that's why I couldn't reproduce it. I don't use that feature of the `dir` segment in my prompt.

Also, that code no longer exists in `powerlevel9k`, actually. Have you tried updating to our latest release? You can either get it [here](https://github.com/bhilburn/powerlevel9k/releases) or by pulling the `master` branch.

**Comment by kcwu** [comment]
Really? I'm using the master, latest revision, cef8c65586c92a6c696b497c0d4ddd6610db203e.

**Comment by kcwu** [comment]
oh, I got what you mean. The code no longer exists in `next` branch. But it still exists in `master` branch.

**Comment by kcwu** [comment]
I found https://github.com/bhilburn/powerlevel9k/pull/275 just addressed exact this issue. I will try `next` branch.
