### ISSUE TITLE
font issues with awesome-terminal-fonts

### ISSUE THREAD

**Issue by shibumi** [bhilburn/powerlevel9k#325]
I am not sure what is going wrong. So I will track this issue here also:

https://github.com/gabrielelana/awesome-terminal-fonts/issues/31

Seems like some font-mapping is going wrong. When vim-devicon is working, my powerlevel9k doesn't work anymore. And when my powerlevel9k works then vim-devicon won't work. Really strange.

**Comment by bhilburn** [comment]
Thanks for the alert, @shibumi. This has to be an issue with `awesome-terminal-fonts`, because we haven't changed our font code points, and it looks like the code points have changed in your screenshots.

Based on the bug you filed in the 'Awesome Terminal Fonts' repo, the commit immediately after <> is what breaks things for you. The commit immediately after is this:

https://github.com/gabrielelana/awesome-terminal-fonts/commit/2600549f216eb3cb78740280393fc437374461ea

...which, unsurprisingly, appears to define a ton of new devicon code points.

If you checkout the HEAD of "Awesome Terminal Fonts", does Powerlevel9k work or does `vim-devicon` work?

**Comment by shibumi** [comment]
Hello @bhilburn ,
The fault lies by "Awesome Terminal Fonts". Their icon mapping is absolutly incompatible with the other projects. I have reported that there. I hope the developer will step back. I am currently using the last stable commit with awesome terminal fonts and everything works fine now. I have vim-airline + vim-devicon. I just needed nerd-fonts on top of awesome terminal fonts. With both fonts it's working now. I will close this issue because it's not really related to your project.
