### ISSUE TITLE
All my icons work except the python icon with virtualenv

### ISSUE THREAD

**Issue by rmad17** [bhilburn/powerlevel9k#338]
I am using Source Code Pro for Powerline. I am attaching a screenshot. 
![py-logo](https://cloud.githubusercontent.com/assets/2450047/20236548/7e1e8e2e-a8de-11e6-9e4d-9313008efd5a.png)

**Comment by dritter** [comment]
Well. It seems like your font does not have the python icon on that codepoint (or maybe not at all). Which [strategy](https://github.com/gabrielelana/awesome-terminal-fonts#patching-vs-fallback) of awesome terminal fonts do you use?

Btw. You could easily change the icon by setting `POWERLEVEL9K_PYTHON_ICON` to whatever icon you have in your font. ;)

**Comment by rmad17** [comment]
I am using patching strategy because I was sure I was going to use only one font `Source Code Pro`..

**Comment by dritter** [comment]
Interesting. The python icon is the ["snake"](http://www.iemoji.com/view/emoji/211/animals-nature/snake) emoji.
So `echo $'\U1F40D'` shows the wrong symbol on your machine, right?

Maybe you need an additional font package to display them (e.g. on [ubuntu linux](http://www.omgubuntu.co.uk/2014/11/see-install-use-emoji-symbols-ubuntu-linux)). In OSX it should work out of the box.

**Comment by rmad17** [comment]
@dritter It did work. Thanks. But I am kind of unsatisfied. I have seen emojis look prettier on my friends Mac.

**Comment by dritter** [comment]
Well, if you find a prettier icon, you can overwrite the default one ;)

**Comment by rmad17** [comment]
Is there any way I can use nerd fonts with the current scenario?

**Comment by dritter** [comment]
Yes, but it takes a little effort. You'll have to overwrite every icon by setting the right environment variables. You can get a full list of icons with `get_icon_names`.

The reason why we do not have a mapping for nerd font is because they change the codepoints depending on the combination of merged fonts. So we cannot give a list of icons for every combination.

**Comment by rmad17** [comment]
Thanks @dritter but I guess I will stick to what I have since it will require some work.

**Comment by cvmocanu** [comment]
There seems to be a bug.

By default ``POWERLEVEL9K_PYTHON_ICON: `` (\ue63c, which seems to be a Chinese character).
I say it's a bug, because I don't see a reason why the Python icon should be a Chinese character, even if there are fonts that support it.

It should be ``\U1F40D`` (snake) or ``\UE73C`` (python logo) instead.

The problem is in ``functions/icons.zsh``.

In addition, on a dark terminal, black font dark blue is hard to read, so I changed it to black on cyan.

To workaroud the bug, I have this in my .zshrc, after including powerlevel9k (to be able to override the function):
```sh
# POWERLEVEL9K_PYTHON_ICON='\U1F40D ' # 🐍
POWERLEVEL9K_PYTHON_ICON='\UE73C '  # 

prompt_virtualenv() {              
 local virtualenv_path="$VIRTUAL_ENV"
 if [[ -n "$virtualenv_path" && "$VIRTUAL_ENV_DISABLE_PROMPT" != true ]]; then
 "$1_prompt_segment" "$0" "$2" "cyan" "black" "$(basename "$virtualenv_path")" 'PYTHON_ICON'
 fi
}
```
