### ISSUE TITLE
Add a logo

### ISSUE THREAD

**Issue by dritter** [bhilburn/powerlevel9k#367]
Here is a late Christmas wish: I'd love for powerlevel9k to have a logo. I mean, we are big enough to have a logo. Time is ripe!

**Comment by bhilburn** [comment]
So I totally agree with this. I asked a friend & PL9k user to design some logos a couple of years ago, actually, and he sent back the following. The form factors are such that I haven't totally figured out how to use them, well. 

I think these could make great banner-style content for PL9k, but we need something that's good as an icon. Do we have any users that are willing to give this a go?

Here are the previously made logos:

![powerlevel9k_ammeter](https://cloud.githubusercontent.com/assets/569571/21550380/77c41310-cdc7-11e6-8f57-e5227114a230.png)

![powerlevel9k_banner](https://cloud.githubusercontent.com/assets/569571/21550383/7b63047c-cdc7-11e6-86e5-709532259955.png)

![powerlevel9k_counter](https://cloud.githubusercontent.com/assets/569571/21550386/7e40c4e0-cdc7-11e6-921e-a8823ad478b5.png)

**Comment by Tritlo** [comment]
I'm in favour of a super minimal one, i.e just ` > :fork: powerlevel9k >"`, in a nice font (I'm partial to terminus and Pramata Pro, but no matter)

**Comment by toish** [comment]
Possibly something minimal? Here's my go at it.

![9k](https://cloud.githubusercontent.com/assets/8439945/21584545/d3c56650-d079-11e6-90d7-a3b7a0475be2.png)

**Comment by bhilburn** [comment]
@Tritlo - Great idea, and agreed. I'm a fan of minimalism, especially is logos.

@toish  - Wow! Nice work. I like this a lot. Like, really a lot.

Would you mind throwing together some mock-ups with the "9K" colored with a few different choices? I'm not sure they will be improvements, but I think it's worth looking at.

No matter what, though, I'm thinking this is the way forward 👍

**Comment by dritter** [comment]
Nice!
I did a quick scribble to throw in another direction. My thoughts were more about putting the shell into super sayan mode. So I thought this might be worth to scribble something like that down and give some of you (whose drawing level is over 9000 ;) ) a new impulse.
![img_20170103_233134](https://cloud.githubusercontent.com/assets/1544760/21625820/e179df34-d20d-11e6-8c88-8f7d3d503343.jpg)

Disclaimer: I might have gotten something wrong. Got my knowledge from Dragonball Z mostly from http://knowyourmeme.com/memes/it-s-over-9000 :D

**Comment by toish** [comment]
@bhilburn Here's some variations!

![pl9k](https://cloud.githubusercontent.com/assets/8439945/21626621/20a29fc6-d1e0-11e6-80e4-2b01640c5439.jpg)

**Comment by rjorgenson** [comment]
Personally I -really- like the black and yellow one in the terminal screenshot and don't really like the largest black on white one. I think the larger the K gets in that font the more the segments separate and the worse it looks. I really like the idea of just 9k or even p9k on a segment background though. It's simple and represents what p9k does, love it =]

**Comment by shibumi** [comment]
@toish DAMN! Your design is awesome! I would like to have this as official logo. I would also go for the logo with black background and white font.

**Comment by bhilburn** [comment]
Wait, this may be a silly question, but is that an actual font you are using for the text, @toish, or is the screenshot just mocked-up? I had assumed that the text in the logo was just drawn, and thus could not actually be rendered in a terminal.

I really like the variations you created, @toish - they look fantastic. I'm a fan of the brighter backgrounds as they 'pop' a bit more. I like the larger one you created with the shadowing, the smaller one with the blue background, and the version with the bright yellow background shown in the terminal. Right now, I'm wondering if there is a good way we could use the larger one with the shadowing as the big official logo at the top of the README, and use one of the smaller ones as an icon / smaller logo / favicon, etc.,

I think with one more iteration we could pick a final option. Would you mind creating a few more color options, and perhaps include a few that say "P9K", as @rjorgenson suggested, just to see what it looks like with three characters instead of two?

@dritter - Rather comically, I also don't know anything about DBZ - I actually never watched it. When I was first making P9K, I just thought that meme was funny and so picked it as a name because of the crossover of the word "power" between the meme and powerline fonts. 

One thing I do know from DBZ though is that when someone goes "super saiyan" it explodes in fire. What would be awesome is if we made a gif of the logo that goes "super saiyan", kind of like your drawing, to use as an emoticon, etc.,

**Comment by toish** [comment]
@bhilburn Yup, just a mock-up, needed someway to visualize the logo "in use" though, could be included in a patched font, so it's not entirely impossible!

I'll try out some new colours + clean up vectors a bit tonight (EST), for now, here's P9K:

![pl9k-2](https://cloud.githubusercontent.com/assets/8439945/21658736/b655986a-d295-11e6-9a2f-26d2f61e7da8.jpg)

**Comment by bhilburn** [comment]
Thanks for the mock-ups!

I'm thinking just '9K' is better. I can't not see two raised fists with the 'P9'. It also just seems harder to read.

Your original idea with just two characters is better =)

**Comment by dritter** [comment]
> @dritter - Rather comically, I also don't know anything about DBZ - I actually never watched it.  When I was first making P9K, I just thought that meme was funny and so picked it as a name because of the crossover of the word "power" between the meme and powerline fonts.

LOL.

> One thing I do know from DBZ though is that when someone goes "super saiyan" it explodes in fire. What would be awesome is if we made a gif of the logo that goes "super saiyan", kind of like your drawing, to use as an emoticon, gif logo, meme, etc., It would also stand out quite a bit from other powerline-based themes.

Indeed. That would we awesome!

So, do we vote on a logo now? If so, I am all in for the light blue "9K" one.
Thank you very much @toish :)

**Comment by toish** [comment]
@polarathene Something like this? (Quickly thrown together on a lunch break)
![pl9k-3](https://cloud.githubusercontent.com/assets/8439945/21692394/a5f3fdbc-d34a-11e6-9894-f7d135b88c37.jpg)

And here's a (*very messy*) AI file! (Not everything is in artboards, open in Illustrator too see everything)
https://adobe.ly/2ifIYfq

Can also export SVGs too, though I think I'll have to expand a couple of the paths

**Comment by polarathene** [comment]
@toish Yes something like that is subtle but feels a little better :) Not sure what others think. Thanks for sharing the source, might have a play around in Illustrator if I can find the time.

**Comment by bhilburn** [comment]
@toish - I'm a fan of that latest one using @polarathene's suggestion of lengthening the stem. Nice work, folks!

@toish - We've had a number of folks say that the small blue variant is their favorite, which I'm happy to hear because it's actually my favorite, too! Would you mind making a new version of the small blue variant and the large one (with the shadowinwg) with the long stem? If you have any other ideas you want to test out & share, I would certainly love to see them. I think we're closing in on the final version, here :)

**Comment by shibumi** [comment]
Yep please the blue one with shadowing @toish

**Comment by toish** [comment]
![Powerlevel 9k logo](https://raw.githubusercontent.com/toish/powerlevel9k-logo/master/logo.png)

I put everything into a repo! https://github.com/toish/powerlevel9k-logo

@bhilburn Got the longer stem version on everything! Can move the repo over to you, I think that'd make more sense than having it on my account

@polarathene That repo should keep things organized if ya have some changes, got a cleaner Ai file on there now too!

**Comment by bhilburn** [comment]
@toish - This is fantastic! I'm going to work on getting it integrated into the README, now. I agree that it probably makes more sense to move the repo over to me. If you're okay with it, I'll pull the repo, push it into my account, and then make you a collaborator on it with full access. Are you okay with a CC-BY-SA license?

**Comment by toish** [comment]
@bhilburn Sounds good! I can transfer it to your github account as well, and yup, that license is good with me!

**Comment by bhilburn** [comment]
@toish - Oh! I hadn't realized that you could transfer repositories in Github. Yes, let's do that - seems easier. Once you initiate the transfer, I'll accept it on my end =)

**Comment by toish** [comment]
@bhilburn Transferred!

**Comment by bhilburn** [comment]
Done! https://github.com/bhilburn/powerlevel9k-logo

Now to integrate it with the PL9k readme...

**Comment by bhilburn** [comment]
Done! Check out the README! I think it looks excellent.

https://github.com/bhilburn/powerlevel9k

This is really fantastic work, @toish, and a great contribution to the project! Thanks so much.

And thanks to everyone who provided their feedback in this thread! @Tritlo @rjorgenson @shibumi @polarathene. And thanks for getting this discussion started, @dritter!
