### ISSUE TITLE
Test New Nerdfont Fontconfig

### ISSUE THREAD

**Issue by bhilburn** [bhilburn/powerlevel9k#410]
@lcorsini @kaymmm 

Okay, I merged @kaymmm's PR for Nerdfont's, which seemed to be largely the same as @lcorsini's. I don't use nerdfonts myself, though, so it's difficult for me to test them and make sure everything is working properly.

Can you guys checkout the latest `next` branch, switch over to `nerdfont-config`, and give it a go? Spot anything wrong? Anything that can be improved?

**Comment by kaymmm** [comment]
Awesome! The `icons_test` came out looking good for me.

**Comment by lcorsini** [comment]
Great, I'll test it tomorrow

**Comment by shibumi** [comment]
Hey, I get the following error when testing the newest next branch:
```build_right_prompt:11: command not found: prompt_detect_ssh ```

**Comment by bhilburn** [comment]
@shibumi - The name of the SSH segment in `next` is just `ssh`, not `detect_ssh`

**Comment by shibumi** [comment]
@bhilburn 
You are right.. seems to have something todo with current zshrc file.. Now I fixed it. How can I test all icons?

**Comment by dritter** [comment]
@shibumi there is a function called `get_icon_names` that dumps all icons.

**Comment by shibumi** [comment]
Hey, there are some icons missing for me:
![](https://paste.archlinux.de/PV8/)
but maybe there is something wrong in my .zshrc:
```
zsh_detect_virtualization(){
    local virt=$(systemd-detect-virt)
    local color='%F{yellow}'
    if [[ "$virt" == "none" ]]; then
        if [[ "$(ls -di / | grep -o 2)" != "2" ]]; then
            virt="chroot"
            echo -n "%{$color%} $virt"
        else
            ;
        fi
    else
        echo -n "%{$color%} $virt"
    fi
}

zsh_detect_ssh(){
    local color='%F{yellow}'
    if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
        echo -n "%{$color%} ssh"
    fi
}

POWERLEVEL9K_CUSTOM_DETECT_VIRT="zsh_detect_virtualization"
POWERLEVEL9K_CUSTOM_DETECT_SSH="zsh_detect_ssh"
POWERLEVEL9K_CUSTOM_DETECT_VIRT_BACKGROUND="black"
POWERLEVEL9K_CUSTOM_DETECT_SSH_BACKGROUND="black"
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time custom_detect_virt custom_detect_ssh)
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time custom_detect_virt detect_ssh)
POWERLEVEL9K_MODE='awesome-fontconfig'
POWERLEVEL9K_SHOW_CHANGESET=true
source  /home/chris/export/github/powerlevel9k/powerlevel9k.zsh-theme
#source  /usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme
#zstyle ':completion:*:hosts' hosts
```

**Comment by dritter** [comment]
@shibumi I don't think there is anything wrong in your `.zshrc`. This Issue is about testing `nerdfont-fontconfig` option. `get_icon_names` prints the icons of your current `POWERLEVEL9K_MODE` - which is in your case `awesome-fontconfig`..

Regarding your missing icons: The icons for battery, python and aws_eb are emojis. You might need to install a [special package](https://wiki.archlinux.org/index.php/fonts#Emoji_and_symbols) to display them.

**Comment by kaymmm** [comment]
It might be worth noting that I changed all three of those emoji to nerdfont icons instead of using emoji because I prefer a more unified look. I did leave the AWS_EB icon as an emoji, however, since I couldn't find any appropriate analogs in the set of nerdfont icons. This might be worth fixing, either by finding an elastic beanstalk icon in the nerdfonts or maintaining consistency with the other font modes and sticking to emoji for all of those icons. 

Obviously, the note about needing to set the mode to nerdfont-fontconfig still applies.

**Comment by shibumi** [comment]
@dritter thanks for the tip! With noto-emoji font installed it's working now. But I have still awesome-font installed.. not sure if nerdfonts+emojis would be enough. But I really like the step away from awesome-terminal-fonts.. awesome-terminal-fonts seems not well maintained anymore. I reported some bugs some months ago.. no reaction.
![](https://paste.archlinux.de/OVwybF/)

**Comment by akrueger** [comment]
@bhilburn To clarify, it is `nerdfont-fontconfig` rather than `nerdfont-config` ?

**Comment by akrueger** [comment]
I had most of the nerdfonts icon dump work except for this particular font.

<img width="1440" alt="screen shot 2017-02-26 at 18 00 26" src="https://cloud.githubusercontent.com/assets/1644520/23345081/b2860bfc-fc4d-11e6-932f-89cd47652035.png">

**Comment by akrueger** [comment]
I was able to use a few of the custom nerdfonts from font-awesome and devicons working, but none of the other glyph sets.

 The powerline segments are choppy and a bit off for all the nerdfonts (but I believe that was expected correct?)

<img width="1440" alt="screen shot 2017-02-26 at 19 41 28" src="https://cloud.githubusercontent.com/assets/1644520/23346000/c6a20092-fc5b-11e6-8d86-1727cddefb39.png">

**Comment by lcorsini** [comment]
Tested it on an Ubuntu 16.10, works like my patch, the only strange icon is aws_eb which seems still emoji.
@akrueger yes, sadly nerdfonts still need some work in that sense, but if you use a poweline patched and fontconfig fallback (or iterm2 fallback on osx) rendering is perfect.
I use Terminus(Terminsess) Powerline as my main font (Its a BCF bitmap font) and the nerdfont version as fallback and everything works

**Comment by akrueger** [comment]
@lcorsini can you describe how to set up a fallback? I'm not familiar with that.

**Comment by bhilburn** [comment]
@lcorsini - Do you have a recommended fix for the AWS icon? Other than that, would you give this the thumbs-up for merge?

**Comment by kaymmm** [comment]
re: the elastic beanstalk icon, what do folks think about just using the
generic Amazon fontawesome icon at \uf270?

>

**Comment by akrueger** [comment]
@kaymmm That would definitely work. I believe the actual AWS glyph is available at `\ue7ad`. It's possible that it's too intricate to look good on a powerline segment, but it would be most appropriate otherwise.

**Comment by lcorsini** [comment]
the was icons are present inside nerd fonts this is a crop from my config file
![aws_fonts](https://cloud.githubusercontent.com/assets/1501930/23396462/3deb4990-fd94-11e6-8d78-154e474e5585.png)
I just printed the file content on terminal and you can see that I put the correct glyph as a comment
I used them, the problem I see is that the beanstalk font is in the same place of an emoji and the OS (the screenshot is from OS X) or the terminal window uses that...
![iterm](https://cloud.githubusercontent.com/assets/1501930/23396536/8b2e61f6-fd94-11e6-8650-43a917a167ad.png)
I think that \U1F331 it's not the same code point that I used there. I have to check with font forge which is the correct codepoint of the EB symbol I used in my patch (see first screenshot)

**Comment by bhilburn** [comment]
@kaymmm @lcorsini @akrueger - This is the last issue I want to close before making our new release :)

Did you find any alternative code points, @lcorsini? @kaymmm also had the suggestion of using \uf270.

**Comment by kaymmm** [comment]
@akrueger You're right about the AWS icon being intricate, and indeed it doesn't look particularly good in the powerline segments, but I already used that icon for `AWS_ICON` in my original pull request ;-) I believe the comment by @lcorsini is in reference to the `AWS_EB_ICON` which I had left as the emoji beanstalk since I couldn't find another suitable replacement. 

@lcorsini it looks like you used `\uf1bd` for `AWS_EB_ICON`. According to the [Font Awesome documentation](http://fontawesome.io/icon/deviantart/), that's the Deviantart icon. But it looks close enough to a beanstalk to me to pass muster.

@bhilburn, I think switching the `AWS_EB_ICON` to either `\uf270` or `\uf1bd` before closing this issue would be a good move to make the nerdfonts consistent in utilizing font icons throughout instead of having a couple of emoji. I don't have a strong opinion between the two options. But congrats and thanks on reaching the new release!

**Comment by akrueger** [comment]
@kaymmm ahh, got it. Makes sense.

`\ue02f` also looks quite a lot like the emoji it would be replacing.

`\uf270` seems more like a candidate for AWS (if you decided the other one was too intricate) rather than beanstalk to me.

I don't personally use AWS or AWS_EB though, so I would be fine with any of them :)

**Comment by lcorsini** [comment]
@kaymmm Yes, I've checked and the icon and it's that one, codepoint `\uf1bd ` for AWS_EB

`\uf270` it the generic amazon logo, not exactly related directy to AWS but more readable
`\UE7AD` it's the AWS logo, which is less readable, but directly related to AWS.
It's probably a matter of personal preference

**Comment by Cpt0r** [comment]
the correct setting for `POWERLEVEL9K_MODE` is 'nerdfont-**font**config'.

Issues:
- majority of icons are still smaller than text
- github icon is gone
- spacing issue with branch icon as per screenshot

Font used: Hurmit

<img width="637" alt="screen shot 2017-03-05 at 17 12 43" src="https://cloud.githubusercontent.com/assets/8690075/23585068/a66d80b4-01c7-11e7-8f1f-8c5cf78a10dc.png">
<img width="640" alt="screen shot 2017-03-05 at 17 13 14" src="https://cloud.githubusercontent.com/assets/8690075/23585069/a6700758-01c7-11e7-9ce8-f851c7dd8e71.png">

Keep up the good work! 👍

**Comment by ryanoasis** [comment]
If there is something in particular we can do from Nerd Fonts end let me know.

Obviously probably fixing some of the issues mentioned here if possible  :wink:

**Comment by bhilburn** [comment]
Thanks for everyone's input on this! I've decided to go with `\uF270`. If we have issues going forward, let's discuss in a new PR.

@ryanoasis - Thanks so much for weighing in, here! Our primary issues with nerdfonts in the past have really revolved around shifting code-points, which is why we haven't added a nerdfont option to P9k until now. Anything that can be done to lock down code-points would be awesome :)

**Comment by ryanoasis** [comment]
@bhilburn Yeah understandable on that. So they are stable it is just that they are shifted only when there is a conflict between sets of glyphs (e.g. Octicons and Font Awesome). However any variation that is of 'Nerd Font Complete' will always have the same codepoints. If for whatever reason that did change we would bump the major version.

Of course there is a patcher that allows to change things but in that case the user would be on their own :wink:
