### ISSUE TITLE
Gap between right side segments using nerd-fonts

### ISSUE THREAD

**Issue by voiprodrigo** [bhilburn/powerlevel9k#427]
Hi,

I'm using nerd-fonts, and this config:

POWERLEVEL9K_MODE="nerdfont-fontconfig"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon ssh dir vcs )
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vi_mode status history background_jobs time)
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='teal'
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M \uF073  %d.%m.%y}"

I see one-pixel gaps between the segments on the right, but not on the left:

![screen shot 2017-03-09 at 18 47 33](https://cloud.githubusercontent.com/assets/2421504/23765379/f1779ba6-04f8-11e7-9911-f43bd37658a5.png)

I'm using 14pt Meslo LG M Regular for Powerline Nerd Font Complete in iTerm2 profile.
Problem goes away if I use regular Meslo Powerline version (but I lose the additional icons so..)
I'm not sure if this is a powerlevel9k issue, or a nerd-fonts issue, please let me know.

Tks.

**Comment by dritter** [comment]
Hmm. We have something like that on our [troubleshooting wiki page](https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting#gaps-between-segments), but I am not sure if that helps you.. I would say this is an issue in Nerdfonts (like [here](https://github.com/ryanoasis/nerd-fonts/issues/29))

**Comment by SirDoctors** [comment]
From my testing I'm only noticing this when using non-mono fonts, when using mono fonts it works as intended.

**Comment by SirDoctors** [comment]
Looks like this is a known issue with nerd-fonts. https://github.com/ryanoasis/nerd-fonts/issues/26

**Comment by voiprodrigo** [comment]
Hi.  Thanks, I commented in https://github.com/ryanoasis/nerd-fonts/issues/26

**Comment by Matows** [comment]
Hello. I think the problem hasn't been fixed. I have the same issue: a gap of 1 pixel between arrows on the right prompt. 
I'm running under Archlinux, I use urxvt with nerd fonts (I installed nerd-font-complete and use Hack Nerd Font Mono)
Seeking for a solution, It turns out that the AUR provides a package "rxvt-unicode-pixbuf" that fixes the issue (although it's not meant for it). I was wondering if that could come from urxvt ?
![powerlevel9k_promp_fail](https://user-images.githubusercontent.com/22861912/59513563-65d50a80-8ebb-11e9-93a0-a4c3088cef25.png)
