### ISSUE TITLE
Improve context segment

### ISSUE THREAD

**Issue by onaforeignshore** [bhilburn/powerlevel9k#459]
I would like to suggest that the context segment be split into host and user segments for the following reasons:
· host and user can be colored separately
· we can add an icon to each (optional)
· host can be made to change color/icon for local and remote hosts
· user can be made to change color/icon for local user/root and remote user/root
· it is easier for the end user to specify which to show than to learn the correct format required by POWERLEVEL9K_CONTEXT_TEMPLATE

**Comment by onaforeignshore** [comment]
I have added prompt_user and prompt_host to my repository. At the moment it does the following:

prompt_user
· changes color & icon based on user / root

prompt_host
· changes color & icon based on local / ssh

Any comments?

**Comment by onaforeignshore** [comment]
<img width="1609" alt="screen shot 2017-03-26 at 14 49 47" src="https://cloud.githubusercontent.com/assets/704406/24330636/f16d101c-1233-11e7-9d06-2d5ee54ef8e1.png">

**Comment by dritter** [comment]
Thanks for your input @onaforeignshore . The stakeholders of such a change would be @bhilburn and @shibumi .

Btw. Your prompt looks nice!

**Comment by DanielGGordon** [comment]
That prompt is a beauty.

**Comment by bhilburn** [comment]
Hey @onaforeignshore - this is a really great idea! I'm re-opening this because I don't want to lose the item. 

Can you file a PR against `next` from your fork? It would be great to start working on getting this merged. One item, though, is that we'll need to maintain the existing monolithic `context` so as not to break existing prompts. So, we would have three segments in total - `context` (current), and then two more that are individual.

**Comment by shibumi** [comment]
@bhilburn so what's the difference to our current solution? Instead of a `ssh` prompt on the right we have an custom icon in front of the hostname + font-color changes. I definitly like this idea! The prompt looks awesome with the icons. I also like the style that he broke with the 'standard' `USER@HOST` prompt and did something like `HOST>USER>PWD`.

@onaforeignshore can you provide your custom `.zshrc` or changes? Would be nice to see it. I am curious now :) 

Maybe you guys have also an idea for an icon for the `virtualization-detection`.. I thought about lightning first but we have this icon already for root.

**Comment by bhilburn** [comment]
@shibumi - The piece of this that's different from what we currently have are a `USER` and a `HOST` segment, which are separate from the `context` segment. Everything else that @onaforeignshore has done in that screenshot is configuration of existing features :) (I think!)

**Comment by onaforeignshore** [comment]
@shibumi - I created two new segments for `user` and `host`, so `context` isn't used.
@bhilburn - also different is coloring the directory separator and changing the color / making bold the last directory path

**Comment by shibumi** [comment]
@bhilburn I like the idea of seperating user and host and getting rid of context. What do you think about this? This would make the SSH part more simple and opens new opportunities.. also: do we have already bold support?

**Comment by bhilburn** [comment]
@shibumi - We can't get rid of `context` entirely because it will break backwards compatibility with configs. As soon as we get the separate segments merged, though, we can move the default configuration over to use them.

We do not already have bold support - that's something new @onaforeignshore is building into #476.

**Comment by onaforeignshore** [comment]
@bhilburn Can we move `context` to deprecated though? (in #476)

**Comment by bhilburn** [comment]
@onaforeignshore - I'd actually like to keep `context` as a supported segment. It's fundamentally different from the separate segments you are creating, and there will likely still be users that want to use it as one monolithic item. 

Moving the default configuration over to using your new segments is something of a "soft" deprecation, though, and will result in the vast majority of our users using the new segments, anyway.

**Comment by shibumi** [comment]
@bhilburn why not building the context segment with @onaforeignshore two segments for host and user? would be just one line at beginning of the code.. something like:

`context="$(user)@$(host)"`

**Comment by bhilburn** [comment]
@shibumi - So, the advantage of the monolithic segment is that it won't break backwards compatibility for folks who are using BASH-expansions. See this line in the code:

https://github.com/bhilburn/powerlevel9k/blob/master/powerlevel9k.zsh-theme#L542

I don't think there is a way to use the split segments and still honor those formatting strings without doing a bunch of parsing, which would be a huge pain in the ass, hah :)

@onaforeignshore - You up for breaking this out into a PR? I would love to get this in for the next release.

**Comment by bhilburn** [comment]
Whoops! Forgot to close this when #489 was merged =)

**Comment by bhilburn** [comment]
Hah, not sure what I was thinking. #489 wasn't merged, it was closed in favor of #497.

Anyway, just leaving this closed since we are discussing in the PR, anyway =)
