### ISSUE TITLE
How to make powerlevel theme work in root mode?

### ISSUE THREAD

**Issue by PrzemekSkw** [bhilburn/powerlevel9k#470]
Like in topic :) 
![tilix](https://cloud.githubusercontent.com/assets/25219988/24724939/526caffa-1a4d-11e7-8c5d-5aa11a375f1e.png)

Can anybody help?

**Comment by thuandt** [comment]
your root shell should be ZSH and has same config as normal user

**Comment by rjorgenson** [comment]
Hi, try using 'sudo -sE' instead of 'su' - The -s will run a shell as root and the -E will preserve your environment. The caveat here is that you won't get root's environment, so you'll need to set root environment things that you want up for your normal user if not already there(things like sbin in path, etc)

**Comment by PrzemekSkw** [comment]
Thx, for help. I don't want to struggle with that and change root shell.

**Comment by rjorgenson** [comment]
@PrzemekSkw try the `sudo -sD` command, it doesn't require changing your root shell at all, it just executes a shell as root and maintains your current environment(shell and all it's settings).

**Comment by bhilburn** [comment]
@PrzemekSkw - The fundamental thing happening, here, is that you configured your shell for you as a user, but not for root. You can either configure root's shell as you have your own, or use some of the suggestions from folks in this thread.
