### ISSUE TITLE
Prompt is not working properly

### ISSUE THREAD

**Issue by maddie** [bhilburn/powerlevel9k#487]
`nerdfont-complete` mode, installed with Prezto.

It looks like this with latest commit:

```
$(print_icon MULTILINE_SECOND_PROMPT_PREFIX)                                            $RPROMPT_PREFIX$(build_right_prompt)$reset_color$RPROMPT_SUFFIX
```

After reverting to 01a5c6a3 the prompt is normal again..

**Comment by qifei9** [comment]
I meet the same issue, with `awesome-patched` mode.

**Comment by bhilburn** [comment]
@maddie @qifei9 - Thanks for reporting this! I merged #486 to fix a security bug in #445, which looks like it may have broken something?

@maddie @qifei9 - Just to double-check:

1) You are using Prezto
2) You are using multi-lined prompt
3) You are using `nerdfont-complete`

My guess is that only #2 matters, but I want to confirm.

We'll want to move quickly to fix this since it is in master. Simply reverting the merge isn't a great option, as that re-introduces the security issue. 

@belak - Any input here would be awesome. @dritter your feedback will be important, as well.

**Comment by Strayer** [comment]
I have the same issue. Using powerlevel9k directly with zplug, no special fonts either. I do have a multi-lined prompt though. Went back to 37174ea for now.

**Comment by qifei9** [comment]
@bhilburn 
- I use zplug
- I use multi-lined prompt, but this issue also occurs in single-lined prompt
- I use `awesome-patched`

**Comment by bhilburn** [comment]
@maddie @Strayer @qifei9 - Thanks for the comments. I have reverted the merge commit. Please checkout the `HEAD` of `master` and confirm that it's now working?

@belak @dritter - Reopening #486 so we can continue the discussion there.

**Comment by qifei9** [comment]
@bhilburn 
It works at 99e59bc83a7b20287306209cecbe732d5c21c46a (current `HEAD` of `master`) and 01a5c6a3a10ff1fea9782607a431ac07652546dc.
The issue occurs at 2817b45f050e753b636ffb471413fef24b193f67 and ae259ff5940420389c6f7175d6f5a844362b56ae.

**Comment by bhilburn** [comment]
@qifei9 - Thanks for confirming! 

I'd like to get one more confirmation that `HEAD` is now fixed. @Strayer, @maddie - Can you test & confirm as soon as you get the chance?

**Comment by Strayer** [comment]
Master seems to work fine for me now on three machines, thanks for the quick fix!

**Comment by bhilburn** [comment]
@Strayer - Thanks for the confirmation! I really appreciate it.

@maddie - Go ahead and update to the latest `master` and you should be good. Thanks again for reporting.

Resolving #445 in a way that doesn't break things is being discussed in #491 for anyone interested.

**Comment by wadkar** [comment]
Thanks @bhilburn for the update; I usually run off `next` branch, and that clearly has this issue. I am working off `master` for now.

Happy to help test out #491 !

**Comment by bhilburn** [comment]
@wadkar - I merged the fix into `next`, as well, so you should be good =)

**Comment by j0hnm4r5** [comment]
I've been getting this issue as well, even with an up-to-date commit: d4a3c045ea9603612f1ee3acc2171331d34eb931. When doing a quick control-c on a prompt (or multiple times in quick succession), I'll get `$RPROMPT_PREFIX$(build_right_prompt)$reset_color$RPROMPT_SUFFIX` instead of my regular prompt.

Using `POWERLEVEL9K_MODE='awesome-patched'` on Oh My Zsh.

**Comment by Elaniobro** [comment]
@j0hnm4r5 I am seeing the same thing when I `ctrl + c`

`~/.zshrc`:
```
POWERLEVEL9K_MODE='awesome-fontconfig'
ZSH_THEME="powerlevel9k/powerlevel9k"
```
