### ISSUE TITLE
Custom keybindings

### ISSUE THREAD

**Issue by shibumi** [bhilburn/powerlevel9k#488]
Hello everybody,
I have developed for me some custom zsh keybindings. At the moment I have these bindings in a seperate project[1], but I had the idea to add this stuff to the powerlevel9k. What do you think about this? It would be something new, because it would add more functionality to the ZSH and not just support via a custom prompt. 

My project zstring adds some string operations to the ZSH. So you can move the cursor on a word and press `CTRL+ALT+"` or `CTRL+ALT+'` for surrounding a string with double or single quotes. If you want to empty the space between the quotes you can just press "CTRL+ALT+;" [2]

[1] https://github.com/shibumi/zstring
[2] https://paste.archlinux.de/tmikd/

**Comment by bhilburn** [comment]
@shibumi - This is really cool! Nice work :)

I don't think incorporating this into P9k is the best decision, though, because as a ZSH theme we have an implicit agreement with our users not to modify the way their shell behaves otherwise (e.g., like modifying their keybindings). As a result of that, users who are looking for this sort of functionality are actually less likely to find your project, because they would never guess to look in P9k.

What about submitting it to OMZ as a plugin? That could be a great way to get wider distribution.

**Comment by shibumi** [comment]
K thanks for your answer. I will close this issue. If someone is interested in `zstring` he can try it out. I will try to get this into grml-config or OMZ.
