### ISSUE TITLE
multiple VCS prompts

### ISSUE THREAD

**Issue by shibumi** [bhilburn/powerlevel9k#505]
Hello,
Maybe this is just an edge-case from me, but how can I enable more than one VCS prompt at the same time?

I have at work many SVN-repositories, but I also track them with git because I prefer git. I use SVN only for checking out and committing stuff and my git is for smaller changes etc.

Any Idea how I could have a git AND a SVN prompt?

**Comment by bhilburn** [comment]
Hm, so, to be honest with you, I think this is a limitation of ZSH's `VCS_INFO` module (which is what we use for the `vcs` segment).

The `VCS_INFO` module only has one global configuration, which is done at P9k's initialization. You would have to re-configure the module twice per prompt rendering in order to display the two segments separately, I believe, which would be pretty painful =(

**Comment by shibumi** [comment]
Mhh sad. But nothing what we can do about it.
