### ISSUE TITLE
Root indicator icon

### ISSUE THREAD

**Issue by jmbelloteau** [bhilburn/powerlevel9k#551]
Just wondering how I could choose my one root indicator icon and background? :)

Thank you

**Comment by onaforeignshore** [comment]
You need to set the environment variable overrides for this. They are:
```zsh
POWERLEVEL9K_USER_DEFAULT_BACKGROUND="18"
POWERLEVEL9K_USER_DEFAULT_FOREGROUND="250"
POWERLEVEL9K_USER_ICON=$'\uF263'							# 
```
to override the user background/foreground and icon, and
```zsh
POWERLEVEL9K_USER_ROOT_BACKGROUND="52"
POWERLEVEL9K_USER_ROOT_FOREGROUND="250"
POWERLEVEL9K_ROOT_ICON=$'\uF198'							# 
```
to override the root background/foreground and icon.

Use your own color combinations and icon designations in place of mine above.

**Comment by jmbelloteau** [comment]
Cool this is working, thank you :)

Just another question, how can I check with fonts powerlevel9k is actually using?
How can I change it if I needed to?

(I'm on ubuntu)

**Comment by onaforeignshore** [comment]
```zsh
#=======================================
# FONT SUPPORT
#=======================================

# NOTE:
# To use the features below, you have to install the font and make it the default font in your terminal emulator.

# For installation instructions for Powerline Fonts
# See: https://powerline.readthedocs.org/en/latest/installation/linux.html#fonts-installation

# Uncomment if you are using Awesome Powerline Font, and you prefer flat segment transitions
#POWERLEVEL9K_MODE="flat"

# Uncomment if you are using Awesome Terminal Font
# See: https://github.com/gabrielelana/awesome-terminal-fonts
#POWERLEVEL9K_MODE="awesome-fontconfig"

# Uncomment if you are using Awesome Patched Font
# See: https://github.com/gabrielelana/awesome-terminal-fonts/tree/patching-strategy/patched
#POWERLEVEL9K_MODE="awesome-flat"

# Uncomment if you are using a Nerd supported font
# See: https://github.com/ryanoasis/nerd-fonts
#POWERLEVEL9K_MODE="nerdfont-fontconfig"
```

**Comment by jmbelloteau** [comment]
@onaforeignshore yes I've read that, I was just wondering how does it work if I have multiple nerdfont install for exemple... which one will be used?

**Comment by onaforeignshore** [comment]
If you have a Nerd Font set as the default font in your terminal, then use `POWERLEVEL9K_MODE="nerdfont-complete"`

**Comment by jmbelloteau** [comment]
'right thank you

**Comment by bhilburn** [comment]
Thanks for providing excellent user support, @onaforeignshore `=)`

Glad you are up and running, @jmbelloteau. In the future, be sure to check out our Wiki:
https://github.com/bhilburn/powerlevel9k/wiki

**Comment by jmbelloteau** [comment]
Sure @bhilburn and I've read before coming here.
But `POWERLEVEL9K_MODE="nerdfont-complete` tell `powerlek9k` to use a bundle of fonts not one in particular. (nerdfont have a lot of different fonts)

So my question was how choose one in particularly for `powerlek9k`

Didn't wanted to bother more @onaforeignshore because he was really kind to help, but I think the question still need an answer :)

**Comment by bhilburn** [comment]
@jmbelloteau - No problem, and the way the fonts work is a common point of confusion. Really, p9k doesn't have a concept of what font you are using - only what code points to use in a family of fonts. Since p9k isn't actually rendering anything itself, it doesn't make sense for it to specify fonts - your terminal emulator does that.

If you could specify a font in P9k, it would end up not mattering because your terminal emulator could ignore it, anyway. All that matters is the code points.

Does that help, at all? If there is a way to improve our docs, I want to be sure we capture that =)

**Comment by jimblue** [comment]
Hi @bhilburn !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

I'll remove this message once it's done!

Cheers

**Comment by jimblue** [comment]
@bhilburn !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

Cheers

**Comment by bhilburn** [comment]
@jimblue - okay, I changed it!

**Comment by jimblue** [comment]
@bhilburn  thanks so much, but you've forget one post 🤕 ! Can you also change it! Thanks again

**Comment by bhilburn** [comment]
okay ,done
