### ISSUE TITLE
Cannot change year part of POWERLEVEL9K_TIME_FORMAT

### ISSUE THREAD

**Issue by carlca** [bhilburn/powerlevel9k#578]
Hello, I've been configuring PowerLevel9K and I'm just about happy with the way it looks, except for the fact that I cannot work out how to change the year display to 4 digits, eg. 2017. 

I've tried changing "%D{%H:%M:%S %d.%m.%y}" to "%D{%H:%M:%S %d.%m.%yy}" and "%D{%H:%M:%S %d.%m.%yyyy}" but all I get is more y's displayed than I know what to do with!

How do I get a 4 digit year? Thanks in advance.

**Comment by rjorgenson** [comment]
Hi carlca 

You'll want to use "%Y" for a 4 digit year instead of "%y" - You can see all the formatting options on the date man page - https://linux.die.net/man/1/date

**Comment by carlca** [comment]
That works perfectly, thanks very much! Just one other question, while I'm here, that you or someone else may be able to answer: Just to the left of the Time/Date block is a left facing arrow which appears to be connected to the Time/Date block. What is it for, and, if I so choose, can I remove it? Thanks!

**Comment by bhilburn** [comment]
@carlca - So glad your problem is solved, and thanks to @rjorgenson for providing support!

@carlca - I'm not sure I understand your new question, actually, as I haven't seen anything like that before. Would you mind filing a new bug and including a screenshot to show us what you are seeing? We'll need to know what font you are using, as well.
