### ISSUE TITLE
Combine prompt elements "dir" and "dir_writable" 

### ISSUE THREAD

**Issue by eumiro** [bhilburn/powerlevel9k#588]
Would it make sense to combine the two prompt elements "dir" and "dir_writable", so that a read-only directory would change the color of the path (to red)?

**Comment by shibumi** [comment]
Damn, I like that idea!

**Comment by bhilburn** [comment]
I agree - that is a really cool idea. Thanks so much for sharing your suggestion, @eumiro!

I want to maintain backwards compatibility, so I think the thing to do, here, is to add the `dir_writable` functionality to `dir`, so that users can choose one or the other in terms of functionality. Since the code already exists in `dir_writable`, this is actually a fairly "easy" PR that someone new to P9k could take on.

I'll let this one hang out for a couple of weeks to see if anyone is interested in submitting this as a contribution =)

**Comment by bhilburn** [comment]
This work was completed by @tippl in #592, and is now part of the v0.6.4 release!
