### ISSUE TITLE
$POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX is ignored

### ISSUE THREAD

**Issue by KSXGitHub** [bhilburn/powerlevel9k#607]
`$POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX` was working, but not after I update p9k

**Comment by bhilburn** [comment]
Can you provide a bit more detail? What branch are you on? Are you using the latest release tag? How are you setting that variable? Can you show screenshots of how it isn't working?

**Comment by KSXGitHub** [comment]
I just do `git pull origin master` (master branch is stable right?)

**Screenshot:**

![image](https://user-images.githubusercontent.com/11488886/29752443-37415918-8b88-11e7-9692-90715c3b2600.png)

I set `POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX` to `  (zsh)  ` (nerdfont-complete), it was working at commit `f8ba6937b9b649602f78c89397ec8e6cdd2c0b23` of powerlevel9k, but after I pull commit `17c069d25ac7b24af6b5dc7ecb9597cef881f582` (a.k.a. branch `master` today), it ignores the variable and display `╰─ ` instead

**Comment by tippl** [comment]
I did a bisect on it some time ago when it was still in next. This variable has changed name because of the new `newline` segment since prompt now can be on multiple lines, so "second" would be incorrect description.
Commit that changed the variable: e844fc4c72e20f84d8022ff9591e75d4a30886cf
Wiki hasn't been updated to reflect this change yet though.

**Comment by bhilburn** [comment]
Whoops! Thanks for pointing this out, @tippl! 

Fixed in the wiki: https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#double-lined-prompt
