### ISSUE TITLE
Status segment fails to handle signals

### ISSUE THREAD

**Issue by julienfalque** [bhilburn/powerlevel9k#609]
Since v0.6.4, when I run a command and stop it with `Ctrl+C`, the `status` segment shows `INT(-2)`. On v0.6.3 it shows `130`.

**Comment by bhilburn** [comment]
Thanks, @julienfalque!

Okay, so this is part of #581, the goal of which is to show the POSIX signal name for return codes. You can set `POWERLEVEL9K_STATUS_HIDE_SIGNAME` to true to go back to the old functionality.

That said, maybe we should discuss how to improve this so it's more intuitive. `INT(-2)` is indicating a POSIX `SIGINT` signal (https://en.wikipedia.org/wiki/Signal_(IPC)#SIGINT), which is what `Ctrl+C` sends.

So, two things:

1. Just showing `INT` maybe is too little? Maybe we should show `SIGINT` if this feature is turned on?
2. What does the `-2`, here, indicate? I'm actually not sure. The `signal` value in POSIX to indicate `SIGINT` is `2` (http://man7.org/linux/man-pages/man7/signal.7.html), but I'm not sure why it's negative, here.

Pinging @docwhat for thoughts, since he was the contributor that implemented this feature in P9k `=)`

**Comment by julienfalque** [comment]
Thanks for the clarification, I thought this was some kind of internal error with `INT` meaning `INTEGER`... This makes more sense to me now :)

1. I agree `SIGINT` would be better than `INT`.
2. Maybe the signal value is shown as negative to match `kill` parameter (i.e. `kill -2 ...` for `SIGINT`)?

**Comment by docwhat** [comment]
The code uses a built in zsh array to look up the signal name.

It’s negative because thats the way I think of the signals in shell. Eg `kill` as mentioned.

**Comment by tippl** [comment]
1. I agree with only writing `INT` being confusing. Maybe make it show the full signal name by default and make the name shortening a config option. Because then it will be the user's decision to get shortened signal name and it won't be confused. Mainly because the most common would probably be `SIGINT` and it is pretty easy to confuse it by the program returning by some mysterous way an integer -2.
2. I think the number of the signal should be left negative, since it makes more sense with signals.

**Comment by julienfalque** [comment]
What about configuration options for both signal name (short/long) and number (positive/negative)?

**Comment by docwhat** [comment]
The problem is that signals vary per platform. The ZSH built in array translates it for us to a short form. There is no array to lookup the long name.

I think the real source of confusion is that people didn’t realize that control-c is sending the INT signal to kill the program.

**Comment by tippl** [comment]
Wouldn't that be just adding `SIG` in front of the short form? We can still use the built-in array with that.

I went over signal(7) and there wasn't a signal without the `SIG`.

**Comment by docwhat** [comment]
I was not sure if by long they meant SIGINT or Interrupt

**Comment by tippl** [comment]
Ah, well i was thinking of using `SIGINT` since that is the name of the signal. And if people have space constraints in their prompts they could set an option to remove the `SIG` since it's redundant. Just that without it, it may be confusing so default would be with.

**Comment by bhilburn** [comment]
@tippl @docwhat @julienfalque - Sorry I went dark there for the last month. September was a pretty insanely busy month for me.

I just pushed to the `next` branch, removing the negative sign and adding `SIG` to the beginning of the name. I'm on the fence about whether or not to keep the actual signal flag numerical value as well as the signal name, but left it for now.

If you can, pull `next` and give it a run for a bit, and let me know what you think! Thanks for everyone's input so far `=)`

**Comment by julienfalque** [comment]
Thanks @bhilburn!
