### ISSUE TITLE
$user doesn't change when using su - makes context prompt not pop up

### ISSUE THREAD

**Issue by ZeGentzy** [bhilburn/powerlevel9k#619]
In line 573 of powerlevel9k.zsh-theme you do this:
`if [[ "$POWERLEVEL9K_ALWAYS_SHOW_CONTEXT" == true ]] || [[ "$USER" != "$DEFAULT_USER" ]] || [[ -n "$SSH_CLIENT" || -n "$SSH_TTY" ]]; then`

However `$USER` doesn't get set to root when you run `su`, so the context menu won't show up if you have `POWERLEVEL9K_ALWAYS_SHOW_CONTEXT` set to false. Using `$(whoami)` instead of `$USER` fixes the issue.

**Comment by bhilburn** [comment]
@ZeGentzy - Sorry it's taken me so long to respond to this! I'm just catching up after a couple of weeks of busy travel.

Nice catch, and thanks for providing an explanation of what's happening! I agree, this needs to be fixed. Is this something you are up for submitting a PR for? If so, please submit it against `master`. Otherwise, let me know and I'll put something together.

**Comment by ZeGentzy** [comment]
I've made a PR for this issue (#636).

**Comment by bhilburn** [comment]
Fixed by merge of #636.
