### ISSUE TITLE
Keep history segment updated when history is shared

### ISSUE THREAD

**Issue by georgewatson** [bhilburn/powerlevel9k#664]
This isn't necessarily powerlevel9k-specific, but it is perhaps something that can be fixed within the theme functions.

In some common workflows (for example using Oh-My-Zsh), the history is shared between all terminals instantaneously. This means that the history number for a line can change before it is even typed, resulting in some confusing behaviour. A simple example of this is shown here:

![screenshot from 2017-11-02 09-46-11](https://user-images.githubusercontent.com/1149280/32319491-ae64eb6e-bfb2-11e7-996f-a9b8b7fbb627.png)

The command `echo Right` was issued after `echo Left`, but both lines appear to have the same history number. In reality, `echo Right` was command 3500. It can thus be difficult to predict, for any given _N_, what the outcome of `!N` will be. (Technically, I've used plain `%h` here, rather than the powerlevel9k `history` segment, but the issue is common to both.)

The most robust "solution" to this problem is to either a) stop using the history segment, or b) turn off history sharing. Neither of these is ideal, as both impact on the desired workflow. One can also develop a habit of hitting enter before typing any command, resetting the prompt, but that's a waste of a keystroke and some screen space.

However, I'm hopeful that there's a way to solve this. The `vi_mode` segment, for example, is updated instantaneously when the mode is toggled, and updates the clock with it—but not the history segment, unfortunately. Is there some way to use a similar hook to update the history segment on one or more of the following events (which I've arranged in rough order of desirability)?
- A command is run in any terminal
- The terminal loses and regains focus
- The command is submitted
- Typing begins

I'm aware this may affect performance, but I imagine I'm not the only person contending with this.

**Comment by bhilburn** [comment]
@georgewatson - Interesting! I'm surprised you're the first person to raise this, honestly. You're right, this is a general problem, but we *might* be able to work around it in P9k. The major hurdle will be doing it in a way that doesn't slow down the terminal dramatically.

So, options (1) and (2) in your list aren't possible (I don't think). Options (3) and (4) are. The issue is that we need ZSH's Line Editor (`zle`) to be invoked to re-draw segments. Even if we had a background process running tracking this, it doesn't have a way of "pushing" an update to a segment because the segment isn't a "listening client".

We currently don't have any `zle` hooks defined in P9k; we used to, but we removed them for performance reasons. This is the relevant portion of the ZSH docs:
http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Zle-Widgets

Fixing this would be a great contribution to the project. I'll put it on my list, but I've got a few other issues / PRs to finish up, first. If anyone else wants to take it on as an intermediate-difficulty PR to P9k, please post here and let me know! It would be greatly appreciated `=)`

**Comment by georgewatson** [comment]
I don't know much about `zle`, but I had a bit of a play.

I tried using the code in PR #320, but found that the history number still wasn't being updated. After some experimentation, I figured out `%h` wasn't being incremented before the prompt was reset. As far as I can tell, that's a problem fundamental to zsh and there's nothing P9k can do about it.

However, I managed to hack together a workaround by redefining `prompt_history` as
    prompt_history() {
        HISTORYSIZE=`grep -c '^:' $HISTFILE`
        "$1_prompt_segment" "$0" "$2" "244" "$DEFAULT_COLOR" "$(($HISTORYSIZE + 1))" 
    }
When combined with the code from #320, this works! However, counting the number of lines beginning with a colon in the history file feels like an ugly hack. I haven't encountered any problems yet, but I wouldn't be surprised if something terrible happens somewhere down the line.

**Comment by georgewatson** [comment]
I somehow just noticed that my fix above mildly breaks the `command_execution_time` segment by causing it to disappear after a command is run.

**Comment by bhilburn** [comment]
I am on a issue-cleaning spree. This issue hasn't had motion in quite some time, and so I am closing it out due to inactivity. If anyone would like to re-open it because they feel it is un-resolved and is something they care about, please feel free to re-raise the discussion!
