### ISSUE TITLE
Installation Instructions are Complicated

### ISSUE THREAD

**Issue by dritter** [bhilburn/powerlevel9k#7]
**Summary:** The installation instructions are overly complex.

**Comment by dritter** [comment]
Whoops. It's too late. I just misread the documentation.
Everything is all right.

**Comment by bhilburn** [comment]
Yeah, I don't like them either, honestly. I just stuck that in there so that it would be something that I knew worked until we could work out something better.

I tried cloning directly into `custom/themes`, but I couldn't make OMZ find the theme. No matter what I tried, I couldn't seem to get it to look in a sub-directory under the `themes` folder (in either `custom/themes` or the default `themes`).

Without the ability to clone directly into the `themes` directory, though, I'm not sure how to improve this. I suppose I could change them to just download the raw file directly into your themes directory... that would work for people who never want to pull updates, I suppose `:-/`

Other ideas / thoughts?

**Comment by dritter** [comment]
Strange that OMZ doesn't find your theme, as in `.oh-my-zsh/oh-my-zsh.sh` is defined where your custom directory is:
```zsh
 # Set ZSH_CUSTOM to the path where your custom config files
 # and plugins exists, or else we will use the default custom/
 if [[ -z "$ZSH_CUSTOM" ]]; then
     ZSH_CUSTOM="$ZSH/custom"
 fi
```
Your `.zshrc` should define what `$ZSH` is:
```zsh
export ZSH=$HOME/.oh-my-zsh
```

Have you set `ZSH_CUSTOM` to another directory?

I am currently using OMZ with powerlevel9k theme cloned into `.oh-my-zsh/custom/themes/powerlevel9k` and set `ZSH_THEME="powerlevel9k/powerlevel9k"`. That setup works fine for me...

I'm on:
zsh 5.0.7
OMZ: e55c715508a2

But I am pretty shure, that you have checked all these options already..

**Comment by dritter** [comment]
Another idea would be to substitute @agnoster original Theme in OMZ. That said, I think I'll try to add the powerlevel9k theme as git-submodule in OMZ. ;)

**Comment by bhilburn** [comment]
WELP. I'm just an idiot.

Works fine. Fixing README...

**Comment by dritter** [comment]
What was the problem? ;)

**Comment by bhilburn** [comment]
My OMZ check-out was a fork of the original project that I had made years ago and gradually tinkered with. I thought I had all of the changes in the original project, but apparently at some point I missed some.

Since I wasn't really using the changes I had made, anyway, I just `reset --hard` to the official master branch, and it started working. I must have missed whatever changesets introduced that capability.

Derp.
