### ISSUE TITLE
custom wifi_signal segment not working

### ISSUE THREAD

**Issue by ghost** [bhilburn/powerlevel9k#721]
![screenshot from 2018-01-14 19-58-22](https://user-images.githubusercontent.com/21981836/34917083-9b077412-f967-11e7-95cb-cee4214a8aff.png)

`zsh_wifi_signal(){
    local signal=$(nmcli device wifi | grep yes | awk '{print $8}')
    local color='%F{yellow}'
    [[ $signal -gt -60 ]] && color='%F{green}'
    [[ $signal -lt -70 ]] && color='%F{red}'
    echo -n "%{$color%}\uf424 %{%f%} $signal%{%f%}"
}

POWERLEVEL9K_CUSTOM_WIFI_SIGNAL="zsh_wifi_signal"
POWERLEVEL9K_CUSTOM_WIFI_SIGNAL_BACKGROUND="black"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir rbenv vcs virtualenv custom_wifi_signal)

#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context dir rbenv vcs virtualenvcustom_wifi_signal)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator command_execution_time background_jobs disk_usage)
POWERLEVEL9K_VIRTUALENV_FOREGROUND='196'
POWERLEVEL9K_VIRTUALENV_BACKGROUND='018'
POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE="true"
`

**Comment by bhilburn** [comment]
Ah, thanks for pointing that out. I'm actually not sure why that's not working anymore, but I'm not terribly surprised that it's bitrotted. Since that's really just example segment code, and not an actual segment, it doesn't get testing in our CI system, and I doubt many people are using it.

Unless there is someone who has a working version of this they are willing to share, I'm partial to just blowing it away and using a simpler example for a custom segment.

@aadeshchandra01 - Have you tried debugging that code at all? Does the command `echo $(nmcli device wifi | grep yes | awk '{print $8}')` show anything useful?

**Comment by aadeshchandra01** [comment]
No, it doesn't show anything.

**Comment by bhilburn** [comment]
@aadeshchandra01 - My bet is that your system isn't using NM or doesn't have `nmcli` installed? If not, you'll need to modify that segment to use whatever wifi management tool you are using (NetworkManager, Wicked, etc.,). 

Since this isn't a segment that has been merged into P9k, that code really isn't portable or have broad compatibility, by any means. You'll need to customize it for your system, I'm afraid. We can probably try to help if you're having issues, but you'll need to post more information about it.

**Comment by aadeshchandra01** [comment]
What more info do I need to provide?

**Comment by alaouimehdi1995** [comment]
Hi, I'm on Ubuntu. your `zsh_wifi_signal` did not work for me. I fixed it. Here is the new `zsh_wifi_signal`:
```
zsh_wifi_signal(){
    local signal=$(nmcli device wifi | grep '\*' | awk '{print $8}')
    local color='%F{yellow}'
    [[ $signal -lt 60 ]] && color='%F{red}'
    [[ $signal -gt 70 ]] && color='%F{green}'
    echo -n "%{$color%}\uf424 $signal%%"
}
```

**Comment by bhilburn** [comment]
I am on a issue-cleaning spree. This issue hasn't had motion in quite some time, and so I am closing it out due to inactivity. If anyone would like to re-open it because they feel it is un-resolved and is something they care about, please feel free to re-raise the discussion!
