### ISSUE TITLE
Usage with Nerdfonts does not show icons in terminal. 

### ISSUE THREAD

**Issue by ThisKappaIsGrey** [bhilburn/powerlevel9k#727]
.zshrc
`ZSH_THEME="powerlevel9k/powerlevel9k"`
 `POWERLEVEL9K_MODE="nerdfont-complete"`
 `POWERLEVEL9K_PROMPT_ON_NEWLINE=true`
`POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(ssh context dir rbenv vcs)`

terminal: iterm2 version: 3.1.5
![image](https://user-images.githubusercontent.com/16870341/35192337-d876828e-fe44-11e7-8f77-5d717526c026.png)

**Comment by ThisKappaIsGrey** [comment]
Never mind, I figured it out :)

**Comment by eknoes** [comment]
Can you share your solution?

**Comment by ThisKappaIsGrey** [comment]
You have to configure the icons yourself in your .ZSHRC. You can find the icons here: http://nerdfonts.com/ . Referenced from here: https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt you can get a list of icons by running `get_icon_names` in your terminal.

**Comment by bhilburn** [comment]
Glad you're all set, @ThisKappaIsGrey!

That said, you really should *not* have to configure each icon yourself. This file in P9k defines the codepoints that we use for each font configuration:
https://github.com/bhilburn/powerlevel9k/blob/master/functions/icons.zsh

If the icons weren't showing up for you, it's possible you selected a Nerdfont where the codepoints were simply way different than the standard ones P9k uses. This does happen occasionally, but really shouldn't be normal practice. I hope this helps!

Closing this since @ThisKappaIsGrey reports that he's got things fixed now, but feel free to re-open if there are still issues.

**Comment by MadRukus** [comment]
Did a fresh install on the theme and the icons show as ? with a box around it. The only icon that displays is the check mark. I've tried the other fonts with the same results.
.zshrc
POWERLEVEL9K_MODE='nerdfont-complete'
ZSH_THEME="powerlevel9k/powerlevel9k"

**Comment by abkl** [comment]
@madruckus you need to manually set it as seen in: https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt (the icon customization section).

**Comment by MadRukus** [comment]
OK I thought @bhilburn said you should not have to configure each icon. Thanks, will give it a go

**Comment by MadRukus** [comment]
@bhilburn was correct. I just created another profile named Powerlevel9K set as default and selected the fonts to and it worked out I did not have to manually set anything. Appreciate the response and suggestion.

**Comment by glazey132** [comment]
I'm running into the same problem @MadRukus. So you made a new profile in Iterm and set it as your default profile, selected Hack Regular Nerd Font Complete as your font and all was well? 

I just did that and it unfortunately didn't work for me.

**Comment by MadRukus** [comment]
One important step is the make sure you set the font in the .zshrc file before specifying the theme.

**Comment by VladimirMikulic** [comment]
I have issue with icons too. I am using Arch Linux with KDE Plasma on it(if anyone is interested). My icons are partially displayed. When i run Terminator icons are displaying as they should and everything works fine. On the other hand when I open Konsole(default terminal on KDE) just first half of icon is displayed, other half is invisible. Could you guys help? I would be really thankful to you, I tried resetting fonts, icons, terminal, reinstalling... None of that worked.

**Comment by dritter** [comment]
Hi @VladimirMikulic , this is a [bug in Konsole](https://bugs.kde.org/show_bug.cgi?id=378124) ([related bug](https://bugs.kde.org/show_bug.cgi?id=390650)). According to [this commit](https://cgit.kde.org/konsole.git/commit/?id=e74cf6c36642247f3f79194da373d01a00645d36) it should be fixed in Konsole 18.12. What version of Konsole do you use?
Related to #971 #794 #854 .

**Comment by VladimirMikulic** [comment]
My Konsole version is 18.12.1. I guess, I'll have to wait until they fix this(hopefully).

**Comment by strujilloc** [comment]
I also had the same problem. To solve I needed to change in my `.zshrc` the position of `POWERLEVEL9K_MODE='nerdfont-complete'`  **before** `ZSH_THEME="powerlevel9k/powerlevel9k"`

**Comment by vaibhavsingh97** [comment]
> I also had the same problem. To solve I needed to change in my `.zshrc` the position of `POWERLEVEL9K_MODE='nerdfont-complete'` **before** `ZSH_THEME="powerlevel9k/powerlevel9k"`

Thanks solved the issue

**Comment by mschmidt271** [comment]
This turned me in circles, as well, for a while (I'm on macOS Catalina with iTerm2), but I got it figured out. First, this from @strujilloc was important:

> I also had the same problem. To solve I needed to change in my `.zshrc` the position of `POWERLEVEL9K_MODE='nerdfont-complete'` **before** `ZSH_THEME="powerlevel9k/powerlevel9k"`

However, I also needed to go to `profiles > text` in iTerm and select "Use a different font for non-ASCII text" (I use Inconsolata for ASCII text) and select Hack Nerd Font for the Non-ASCII font.
