### ISSUE TITLE
More POWERLEVEL9K Icon and Color Variables, please!

### ISSUE THREAD

**Issue by jrcharney** [bhilburn/powerlevel9k#728]
I love how Powerlevel9K has the appearance that goes along with enhancements for Vim and Tmux, but there is a lot of stuff PL9K needs to add to complete with projects like [Spaceship prompt](https://github.com/denysdovhan/spaceship-prompt). [Nerdfonts](http://nerdfonts.com/) has the icons for things like React and it would be great to set the colors and icons for it. But the documentation for PL9K is lacking.

**Comment by bhilburn** [comment]
@jrcharney - Thanks for the feedback! We would love to have additional segments (e.g., React), and we do our best to work with people who want to contribute them. If there is a segment that you especially want to see, let us know or post a PR! We would love to work with you to get it upstreamed. If there are areas of documentation that are lacking and thus causing you problems, please post an issue about that specifically, or file a PR to fix it! 

I'm going to close this issue since it's not really specific to anything. Cheers!
