### ISSUE TITLE
wrong current_path under certain circumstances

### ISSUE THREAD

**Issue by anthraxx** [bhilburn/powerlevel9k#731]
Not sure why it sometimes happens and now always, but in a mounted directory i get something that looks like the variable name instead of the actualy pwd content.
No shortening option is enabled.

> ~current_path

actually it should look like this:

> /mnt/usb0/tmp

It has to do with `powerlevel9k.zsh-theme` via https://github.com/bhilburn/powerlevel9k/blob/master/powerlevel9k.zsh-theme#L812
If i remove the -P everything seems to work as expected

**Comment by bhilburn** [comment]
@anthraxx - Thanks for filing this bug! And great debugging! Very interesting that removing the `-P` fixes it. Looking at the ZSH docs for `print`, that flag does:

```
-p

    Print the arguments to the input of the coprocess.
```

To be honest, I don't really see how that flag is relevant to what we are doing because there isn't really a coprocess, here.

@dritter - Can you think of any harm in removing that flag?

**Comment by anthraxx** [comment]
very gentle bump :smile_cat:

**Comment by bhilburn** [comment]
@anthraxx - Sorry, and thanks for the bump! I think we're good to proceed with just removing the flag. Are you up for submitting a PR for it? `=)`

**Comment by anthraxx** [comment]
pull request opened: #776

**Comment by bhilburn** [comment]
Closing this issue to continue the discussion in the PR itself, #776, which is bitrotting at the moment.
