### ISSUE TITLE
Readme for shorten strategy for dir segment is ambiguous

### ISSUE THREAD

**Issue by dualscyther** [bhilburn/powerlevel9k#735]
The current README says that the default value for `POWERLEVEL9K_SHORTEN_STRATEGY` is "None". It also says that the `POWERLEVEL9K_SHORTEN_DIR_LENGTH` is 2.
In the table which defines which each of the different strategies do, the default strategy is listed as "truncate whole directories from left".

The default behaviour could be interpreted as either:
- truncate the path such that it only shows 2 directories.
- don't perform any truncation

Currently, the latter option is what happens (which I agree is good default behaviour). What actually happens is that there is no path shortening unless:
- `POWERLEVEL9K_SHORTEN_STRATEGY` is set
  - Then `POWERLEVEL9K_SHORTEN_DIR_LENGTH` defaults to 2
- `POWERLEVEL9K_SHORTEN_DIR_LENGTH` is set
  - Then `POWERLEVEL9K_SHORTEN_STRATEGY` defaults to .. default (truncate directories)

This is a bit unintuitive.. A simple fix would just be to actually provide a `none` option and a `truncate_folder` option - rather than needing to set `POWERLEVEL9K_SHORTEN_DIR_LENGTH` in order to experience the default `truncate_folder` behaviour.

**Comment by bhilburn** [comment]
Hey @dualscyther - Thanks so much for the feedback! I can see how the current docs might create confusion.

I agree, adding a `truncate_folder` option rather than `default` is more intuitive, and makes the `SHORTEN_DIR_LENGTH` field more immediately understandable. This is a fairly easy fix, as we can create the new option and ghost default to it, thus preserving backwards compatibility with configs.

Are you up for creating a PR for this?

(My apologies for the long delay in getting back to you, by the way!)

**Comment by dualscyther** [comment]
Sure

**Comment by bhilburn** [comment]
Closing this in favor of tracking it in #793
