### ISSUE TITLE
Distro-specific icons

### ISSUE THREAD

**Issue by jennydaman** [bhilburn/powerlevel9k#751]
Is there a way to monkey patch `os_icon` for it to display distro-specific icons (from https://github.com/Lukas-W/font-logos)?

**Comment by onaforeignshore** [comment]
Only 5 of the distros that you have in the link above are not available using a Nerd Font. You can use the following codepoints to override `POWERLEVEL9K_LINUX_ICON` with any of the following:

**Linux Distro icons**
- \uF300 - Arch Linux
- \uF301 - CentOS 
- \uF30F - CoreOS
- \uF302 - Debian
- \uF311 - Elementary OS
- \uF303 - Fedora (and inverse icon \uF312)
- \uF30E - FreeBSD
- \uF310 - Gentoo
- \uF304 - Linux Mint (and inverse icon \uF305)
- \uF306 - Mageia
- \uF307 - Mandriva
- \uF308 - OpenSUSE
- \uF309 - Red Hat
- \uF313 - Sabayon
- \uF30A - Slackware
- \uF17C - Tux (or \uE712)
- \uF30C - Ubuntu (and inverse icon \uF30D)

**Related icons**
- \uF179 - Apple (or \uE711)
- \uE7B0 - Docker
- \uE722 - Rasberry Pi

**Missing icons**
- Alpine
- AOSC OS
- Devuan
- Manjaro
- NixOS

**Comment by onaforeignshore** [comment]
If you have a BSD-based system, use `POWERLEVEL9K_FREEBSD_ICON`. Or use `POWERLEVEL9K_APPLE_ICON` for macOS.

**Comment by bhilburn** [comment]
@onaforeignshore - That's a super useful post! Thanks so much for sharing that!

@jennydaman - If you aren't sure how to overload icons, you can simply export them in your zshrc. See this section in the wiki: https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#icon-customization

As another option, you could just make a new custom segment that simply printed the icon you wanted rather than overloading the `os_icon`. Your custom command would just be to echo the icon you want: https://github.com/bhilburn/powerlevel9k#custom_command

**Comment by sambadevi** [comment]
I am currently working on a pr to support `os_icons` for multiple distros thanks @onaforeignshore for the great list!

**Comment by jennydaman** [comment]
@onaforeignshore thank you so much for that list! Before submitting this issue, I was trying to find the appropriate encoding, but no luck...

This works great. `OS_ICON='\uF300'`

@sambadevi I'm looking forward to your PR

**Comment by bhilburn** [comment]
@jennydaman - Glad you're all set!

@sambadevi - That sounds excellent. I look forward to it!

**Comment by sambadevi** [comment]
@jennydaman @bhilburn you can take a look at it here: #755 

Also if you want to try it yourself (and you are using `antigen`) you can replace the `bhilburn/powerlevel9k powerlevel9k` line in your `.zshrc` with 
```
antigen theme https://github.com/sambadevi/powerlevel9k@next powerlevel9k
```
And use the `os_icon` segment on one of the supported distros:
- Arch Linux
- CentOs
- CoreOS
- Debian
- ElementaryOS
- Fedora
- Gentoo
- Linux Mint
- Mageia
- OpenSuse
- Sabayon
- Slackware
- Ubuntu

Note:

Unfortunately only nerd fonts are supported

**Comment by ryanoasis** [comment]
Just FYI we are working on updating Nerd Fonts with the latest font linux _(now font logos)_: https://github.com/ryanoasis/nerd-fonts/issues/157

This is going to be in the next release, originally supposed to be 1.3.0 but the codepoints ordering of the various distros has changed (on font-logos end not on Nerd Fonts end, so instead of working around that we are going to use the same ordering with the same offset). <- I.e. there will be breaking changes, therefore next version likely to be major (2.0.0).

Here is the mapping we have currently:

### Nerd Fonts font-logos WIP updates

| Code         | Name                |
| -------------|:-------------------:|
| `f300`       | alpine              |
| `f301`       | aosc|
| `f302`       | apple|
| `f303`       | archlinux|
| `f304`       | centos|
| `f305`       | coreos|
| `f306`       | debian|
| `f307`       | devuan|
| `f308`       | docker|
| `f309`       | elementary|
| `f30a`       | fedora|
| `f30b`       | fedora inverse|
| `f30c`       | freebsd|
| `f30d`       | gentoo|
| `f30e`       | linuxmint|
| `f30f`       | linuxmint inverse|
| `f310`       | mageia|
| `f311`       | mandriva|
| `f312`       | manjaro|
| `f313`       | nixos|
| `f314`       | opensuse|
| `f315`       | raspberry pi|
| `f316`       | redhat|
| `f317`       | sabayon|
| `f318`       | slackware|
| `f319`       | slackware inverse|
| `f31a`       | tux|
| `f31b`       | ubuntu|
| `f31c`       | ubuntu inverse|

Any thoughts welcomed.

**Comment by mlopezcoria** [comment]
> @onaforeignshore thank you so much for that list! Before submitting this issue, I was trying to find the appropriate encoding, but no luck...
> 
> This works great. `OS_ICON='\uF300'`
> 
> @sambadevi I'm looking forward to your PR

Where do I have to insert this to change the logo?
Thanks
