### ISSUE TITLE
Unable to get awesome glyphs working with 'awesome-fontconfig' or 'awesome-patched'

### ISSUE THREAD

**Issue by sanjaychaudhuri** [bhilburn/powerlevel9k#765]
Had installed the fonts as explained in https://blogs.technet.microsoft.com/jessicadeen/linux/macos-ohmyzsh-tmux-vim-iterm2-powerlevel9k-badass-terminal/ for MacOS (MacOS 10.13.3) , however could not get it to work with
#POWERLEVEL9K_MODE='awesome-fontconfig'
or 
#POWERLEVEL9K_MODE='awesome-fontconfig'

Changing POWERLEVEL9K_MODE='agnoster' made it work to a certain degree. 

Here is a the output from "get_icon_names"
OWERLEVEL9K_ANDROID_ICON: And
POWERLEVEL9K_APPLE_ICON: OSX
POWERLEVEL9K_AWS_EB_ICON: 🌱
POWERLEVEL9K_AWS_ICON: AWS:
POWERLEVEL9K_BACKGROUND_JOBS_ICON: ⚙
POWERLEVEL9K_BATTERY_ICON: 🔋
POWERLEVEL9K_CARRIAGE_RETURN_ICON: ↵
POWERLEVEL9K_DISK_ICON: hdd
POWERLEVEL9K_EXECUTION_TIME_ICON: Dur
POWERLEVEL9K_FAIL_ICON: ✘
POWERLEVEL9K_FOLDER_ICON:
POWERLEVEL9K_FREEBSD_ICON: BSD
POWERLEVEL9K_GO_ICON: Go
POWERLEVEL9K_HOME_ICON:
POWERLEVEL9K_HOME_SUB_ICON:
POWERLEVEL9K_KUBERNETES_ICON: ⎈
POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR:
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR: 
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR: 
POWERLEVEL9K_LINUX_ICON: Lx
POWERLEVEL9K_LOAD_ICON: L
POWERLEVEL9K_LOCK_ICON: 
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX:
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX: ╰─
POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX: ├─
POWERLEVEL9K_NETWORK_ICON: IP
POWERLEVEL9K_NODE_ICON: ⬢
POWERLEVEL9K_OK_ICON: ✔
POWERLEVEL9K_PUBLIC_IP_ICON:
POWERLEVEL9K_PYTHON_ICON:
POWERLEVEL9K_RAM_ICON: RAM
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR: 
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR: 
POWERLEVEL9K_ROOT_ICON: ⚡
POWERLEVEL9K_RUBY_ICON:
POWERLEVEL9K_RUST_ICON:
POWERLEVEL9K_SERVER_ICON:
POWERLEVEL9K_SSH_ICON: (ssh)
POWERLEVEL9K_SUNOS_ICON: Sun
POWERLEVEL9K_SWAP_ICON: SWP
POWERLEVEL9K_SWIFT_ICON: Swift
POWERLEVEL9K_SYMFONY_ICON: SF
POWERLEVEL9K_TEST_ICON:
POWERLEVEL9K_TODO_ICON: ☑
POWERLEVEL9K_VCS_BOOKMARK_ICON: ☿
POWERLEVEL9K_VCS_BRANCH_ICON: 
POWERLEVEL9K_VCS_COMMIT_ICON:
POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON:
POWERLEVEL9K_VCS_GIT_GITHUB_ICON:
POWERLEVEL9K_VCS_GIT_GITLAB_ICON:
POWERLEVEL9K_VCS_GIT_ICON:
POWERLEVEL9K_VCS_HG_ICON:
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON: ↓
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON: ↑
POWERLEVEL9K_VCS_REMOTE_BRANCH_ICON: →
POWERLEVEL9K_VCS_STAGED_ICON: ✚
POWERLEVEL9K_VCS_STASH_ICON: ⍟
POWERLEVEL9K_VCS_SVN_ICON:
POWERLEVEL9K_VCS_TAG_ICON:
POWERLEVEL9K_VCS_UNSTAGED_ICON: ●
POWERLEVEL9K_VCS_UNTRACKED_ICON: ?
POWERLEVEL9K_VPN_ICON: (vpn)
POWERLEVEL9K_WINDOWS_ICON: WIN

So not able to see HOME and the other ones. Can you help me please for me to find out what else needs to be done ? 

Thanks

**Comment by onaforeignshore** [comment]
You need to remove the `#` from the beginning of the line. In Shell script, `#` indicates that whatever follows will be a comment.

**Comment by sanjaychaudhuri** [comment]
Yea, I understand. I had tried with both of those and none worked. These are in my current configuration and the only one that works is: POWERLEVEL9K_MODE='agnoster' which is uncommented. I prefer to leave all the configurations, enabling/disabling as needed by '#'

#POWERLEVEL9K_MODE='awesome-fontconfig'
#POWERLEVEL9K_MODE='awesome-patched'
#POWERLEVEL9K_MODE='awesome-config'
#POWERLEVEL9K_MODE='default'
#POWERLEVEL9K_MODE='nerdfont-fontconfig'
POWERLEVEL9K_MODE='agnoster'

**Comment by onaforeignshore** [comment]
There is also `awesome-mapped-fontconfig` and `nerdfont-fontconfig` will be called `nerdfont-complete` in the future

**Comment by onaforeignshore** [comment]
Have you installed a nerd font? You can get them [here](https://nerdfonts.com/)

**Comment by sanjaychaudhuri** [comment]
As given in https://github.com/ryanoasis/nerd-fonts#option-4-homebrew-fonts, I installed the fonts using the command:
_brew tap caskroom/fonts
brew cask install font-hack-nerd-font_

I changed my configuration to POWERLEVEL9K_MODE='nerdfont-complete' and changed the Font configurations as shown below and the glyphs. Thanks for helping out with this.

Couple of quick questions:
1. Had installed the powerline fonts as explained here but that did not seem to work. Why is that ?
https://blogs.technet.microsoft.com/jessicadeen/linux/macos-ohmyzsh-tmux-vim-iterm2-powerlevel9k-badass-terminal/ 

2. awesome-mapped-fontconfig/awesome-patched/flat none works after the nerd had been installed as well. Is there a reason for that ?

3. I had followed https://gist.github.com/kevin-smets/8568070 to set the name of the theme to 'https://gist.github.com/kevin-smets/8568070' and also found a file under ~/.oh-my-zsh/themes/gnoster.zsh-theme which I thought was used for this theme


<img width="920" alt="screen shot 2018-03-05 at 8 00 32 pm" src="https://user-images.githubusercontent.com/880560/37010172-eba1a676-20af-11e8-9705-e8670a0c0549.png">

<img width="1161" alt="screen shot 2018-03-05 at 7 58 59 pm" src="https://user-images.githubusercontent.com/880560/37010146-bbc163ec-20af-11e8-830d-a4a9a5ff16bf.png">

**Comment by bhilburn** [comment]
So, there's a lot going on in this thread, and I'm not sure I'm following it all, to be honest with you. Some items:

1. There is no `agnoster` mode for P9k - the two themes aren't related other than both using Powerline fonts. What you actually did was just tell P9k to use it's default configuration, which also functions as a catch-all for configs it doesn't recognize.
2. Copy / Pasting icon output doesn't work because it depends on each individual's browser to render that font code point. If you want to show us the output of `get_icon_names`, it'll need to be a screenshot.
3. I think I'm actually confused, now, about what problem is outstanding? I will note, though, that your separators appear broken in that screenshot, which looks like [this problem described in the Wiki](https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting#background-transparency).

**Comment by sanjaychaudhuri** [comment]
After installing nerdfont as advised, it worked as expected. We can close the issue.

I was curious to know why it didn't work for me even though I followed https://blogs.technet.microsoft.com/jessicadeen/linux/macos-ohmyzsh-tmux-vim-iterm2-powerlevel9k-badass-terminal/   I could only get this to work once I installed nerdfont.

**Comment by bhilburn** [comment]
@sanjaychaudhuri - I'm glad you're all up and running! And it's totally possible that code-points in the fonts changed, which happens from time to time. Fonts are hard! =)

**Comment by rwmitchell** [comment]
Is it possible to dynamically change POWERLEVEL9K_MODE inside an active shell?

I change dynamic profiles in iTerm from the command line to switch fonts.
FiraCode supports ligatures, but lacks awesome.
SourceCodePro+Powerline+AwesomeRegular is awesome, but lacks ligatures.

I'd like to be able to switch between the two, but currently it appears to require changing .zshrc and reloading it before the new font works.

**Comment by bhilburn** [comment]
@rwmitchell - No, it's not possible to change them, I'm afraid. This will be even more true in the next release where we are pre-loading more things to speed up the runtime. Sorry!

**Comment by rwmitchell** [comment]
Guess I can hope more fonts support both Awesome icons and ligatures - or maybe someone can suggest ones that do?

Thanks for the response and the heads up!

**Comment by bhilburn** [comment]
@rwmitchell - Have you checked out @ryanoasis's nerdfonts collection? Not sure if he has any in there that do, but it's worth a check for sure.

**Comment by AzySir** [comment]
@bhilburn This thread is good because it refers to having the symbols in the terminal which is what most people want. 

These instructions are a little ambiguous so @sanjaychaudhuri has addressed that.

Thanks @sanjaychaudhuri !

Option 2: Use a Programmer Font
There are now some fonts, meant specifically for software programmers, that not only provide the necessary powerline glyphs but may also have some of the additional glyphs from Font Awesome. The most well-known are Adobe Source Code Pro and Source Code Pro, which are usually available from your OS's package manager.

NOTE: The default "programmer" fonts have some of the glyphs, like the segment separators, but are missing many others. If you plan to use anything more than the basic glyphs, you'll need a patched version of those fonts, like those you would find in Options 3 and 4, below.

Once you have installed the font, configure your terminal to use that font. Powerlevel9k should then work immediately, with no additional configuration.

These fonts usually also have some of the icons from the 'Awesome Font' special character set. If you wish to take advantage of the additional glyphs, put the following in your ~/.zshrc before you specify the powerlevel9k theme:

POWERLEVEL9K_MODE='awesome-fontconfig'
