### ISSUE TITLE
Is it possible to show execution timer for lines in the terminal output

### ISSUE THREAD

**Issue by sidazhang** [bhilburn/powerlevel9k#768]
For example:
```
sleep 5
echo "hello 1"
sleep 5
echo "hello 2"
```
Actually show the timer on the right prompt
```
hello 1                                      5 DUR
hello 2                                      10 DUR
```

This would be very useful for very long running processes so I can gauge progress over time (how long certain things took)

**Comment by kentmartin73** [comment]
Hi,

Depending on what you mean, I don't see how this would be possible.  If you are talking about running a script with that content, then, there is no prompt issued during the script execution.

If you simply paste those commands into a terminal, then, you'll get the effect you want, albeit at the sleeps, because they're the things that actually take the time.

I had a bit of a play around with trying to force zsh to take each line of some sort of stdin in (pipe, redirect from somewhere etc) and use it as interactive input, which would give you what you want, but, short of an expect script, I didn't come up with anything - I am sure someone will though.

In any event, not something I can see fitting into powerline directly, it is more a question of how you invoke your commands :)

**Comment by bhilburn** [comment]
Have you tried our `command_execution_time` segment? It does exactly what you're asking for, I think?

https://github.com/bhilburn/powerlevel9k#command_execution_time

**Comment by kentmartin73** [comment]
Aha.. assumed he'd gotten that far :)

**Comment by sidazhang** [comment]
@bhilburn I already use command_execution_time

I meant it as to time every line of stdout

like

```sh
script.sh

sleep 5
echo "hello 1"
sleep 5
echo "hello 2"

```

```cmd
sh script.sh
-> hello1               5 SEC
-> hello2             10 SEC
```

**Comment by bhilburn** [comment]
@sidazhang - Sorry, this one got lost there for... 7 months =(

Anyway, the short answer is no, there isn't really a way for us to do this. The prompt will only get redrawn in between command executions. So, P9k could tell you how long it took the entirety of `script.sh` to run, but not each command inside of it.
