### ISSUE TITLE
`fatal: Not a git repository`, when using "vcs" element, in every non-git directory

### ISSUE THREAD

**Issue by rootwork** [bhilburn/powerlevel9k#784]
Setup:
> macOS 10.12.6
> git version 2.14.1
> zsh 5.2 (x86_64-apple-darwin16.0)
> oh-my-zsh commit 2ff956
> powerlevel9k commit afb738

If I include "vcs" in my list of prompt elements -- for instance, in my `.zshrc` file:

`POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(ssh context dir dir_writable vcs)`

In any directory that is not a git repo, I get the following error message printed twice at _every_ prompt:

> fatal: Not a git repository (or any of the parent directories): .git

Now it certainly makes sense that folders that have no git repo initiated (no `.git` subdirectory) have no information to pass to the vcs element.

But is there a way to do an "if" check to conditionally show this element when the current directory is in a git repo, rather than erroring? It seems like it's also slowing down the prompt a bit, in addition to being a lot of visual noise.

Thanks!

**Comment by bhilburn** [comment]
@rootwork - That's actually the way the segment is supposed to work (it only checks if you're actually in a git repo), and I've never seen it behave the way you describe. Something is strange. Our systems are fairly similar, although I do have slightly more recent versions of most of the SW.

Anyway, something really seems to be going bad, here. Are you using any OMZ plugins that might affect git? You're at the HEAD of `master`, so if this issue was widespread, there would be thousands of people with the same problem. I have a feeling this is some corner case in versioning or config.

**Comment by bhilburn** [comment]
Hey @rootwork - just a ping, here! @Jahhein's suggested debug steps are good. Any luck?

**Comment by dritter** [comment]
My best guess is that you have some git wrapper script that causes that error. Luckily @guicassolato addressed this issue in #797 . It would be super helpful if you could try out that branch and see if your error goes away.

**Comment by bhilburn** [comment]
Going to close this one out due to inactivity!
