### ISSUE TITLE
Discussion: Speed vs Flexibility

### ISSUE THREAD

**Issue by dritter** [bhilburn/powerlevel9k#817]
As you all know, we are in the process of merging #771 into `next`. There we came up with the question if we should sacrifice some flexibility for speed. I'll try to sketch some cases here.
Btw. "Flexibility" is the wrong word, cause both Opportunities are flexible.. Bear with me.

To vote either choose 🎉 (Choice 1; Flexibility) or 😄 (Choice 2; Speed) as a [Reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/).

### Current State
The current state of P9K is that you could change almost every variable anytime. So, for instance, if you want to change the Background Color of your `dir` segment, just write out `POWERLEVEL9K_DIR_HOME_BACKGROUND="green"` and it will change to green as soon as you hit enter. Few other variables do not work this way. Most prominent example is here the `POWERLEVEL9K_MODE`. This cannot be changed without re-sourcing P9K (in last consequence: Shell restart).

### State now implementation in the code separation branch
A new aspect that is introduced via #771 is that the segments are separate files, so they need to be loaded separately. We do that by checking which segments are currently active, and loading only that files that are needed (this mechanism is where [the discussion](https://github.com/onaforeignshore/powerlevel9k/commit/bbf597e5658eb9431e33bb2bd4ecbffed76c7941) between Chris and Me started).

### Choice 1: Flexibility 🎉 
This is basically the current state (see above). But we should work on `POWERLEVEL9K_MODE` etc. to be able to change it anytime.
Downsides are: We need to check for everything every time. So whenever the user hits enter, we need to check for every icon override, every color override, etc.

### Choice 2: Speed 😄 
The main idea here is to do as much as possible upfront. My claim here is that we have at least 99% execution time, and only 1% of the time where the user changes his prompt. So we should optimize for the 99%.
This includes: every `set_default` should be outside of the functions, `prompt_icon` no longer checks for overrides (should be done upfront), `left/right_prompt_segment` no longer checks for color overrides, Segments are loaded only once at startup, etc.
Downsides are: Major change in behavior (I expect a lot of support tickets here). The user must restart his shell (or we implement a command `p9k_reinitialize_prompt`). Lastly the Variables must be declared _before_ the theme is sourced (the old `POWERLEVEL9K_MODE` problem).

Speaking in Code:
```zsh
function print_icon() {
  local icon_name=$1
  local ICON_USER_VARIABLE=POWERLEVEL9K_${icon_name}
  if defined "$ICON_USER_VARIABLE"; then
    echo -n "${(P)ICON_USER_VARIABLE}"
  else
    echo -n "${icons[$icon_name]}"
  fi
}
```
This is currently done every time an icon is printed. This could be drastically shortened, if we define icon overrides upfront:
```zsh
function print_icon() {
  echo -n "${icons[$1]}"
}
```

@onaforeignshore Correct me, if I forgot something (or if am too biased ;) ).

**Comment by onaforeignshore** [comment]
Personally, I don't see the issue with the testing of loaded segments, since it only checks if an item is in an array, which is not that costly IMHO.

**Comment by dritter** [comment]
Loading only segments in use dynamically is only one aspect of that. That alone may not be costly, but the almost-no-cost factors add up quickly. Especially if they are executed while rendering every segment (like checking for color overrides). And being a matter of principle, I think we should switch to either side. Mixing the principles confuses people too much (looking at the MODE fiasco).
It also might not compelling to pre set all variables except loading the segments. Not being able to set the background color for segment `X`, but being able to set segment `Y` dynamically might not be evident to the user.

So looking at the whole package, what poison would you choose?

**Comment by onaforeignshore** [comment]
In terms of speed, I would expect each segment to set its own defaults (outside of a function).

Currently, icons are set by calling `registerIcon`, which now checks for user overrides before setting the appropriate icons (as suggested above).

I would suggest a `registerSegment` function be called at the end of the segment definition file (outside of the prompt function). This functions should then either:
1. check for user overridden items and change the _default internal variable_ that was set or
    - environment is kept cleaner as internal variables are used
2. _set all the environment_ variables for each segment based on override or default (colours, bold, etc.)
    - environment becomes more 'cluttered' but user can see the values for each segment easily, as well as change them at any time (for that session as they are not saved across sessions).
3. _create arrays_ to hold the values
    - environment is kept cleaner as internal variables are used
    - all values are stored in just a few arrays

General Advantages:
- Overrides are checked once at initialization
- Drawing speed increases as values are known and no tests are required

General Issues:
- All segments have to set defaults outside the `prompt_` function or they will override the settings.

My preference would be to have all the settings in associative arrays, as that would be the fastest (and this approach is already used in the `zsh-async` branch, so should be easier to implement in the default one)

@dritter @bhilburn What do you think?

**Comment by bhilburn** [comment]
Thanks for posting this and for sharing your thoughts, @dritter and @onaforeignshore!

So, realistically, I think P9k provides far more flexibility than anyone actually uses, and we are doing it at the expense of speed, which **everyone** actually cares about. As @dritter said, right now, you could change a segment's color from draw-to-draw. But, no one does that, and if they did, creating a P9k state array that maps to colors and then just changing the state would be more efficient (as @onaforeignshore pointed out). Similarly, I also don't think users are changing the segments they have loaded from prompt-to-prompt, and as a usage model, I think that's clunky, anyway.

Further, we have clearly seen the effect of slowness in prompt rendering, and it's painful. Most of the users we have lost have been due to this slowness.

I think the best route is that we do **as much as possible** up-front, when the segment is loaded. If there are things that we want to be flexible, for example, if a segment has different states that map to different colors or icons, our associative array approach can be used to enable that. The associative array that holds those states must have been set when the segment was loaded, but the user can change between those loaded states while running.

I think there may be aspects of @onaforeignshore's comments that I didn't address, but I'm not sure. Happy to hear other opinions & feedback on the above!

**Comment by dritter** [comment]
@robobenklein Yes, precompiling P9K is on my list, but I hadn't had time to take a deeper look into that. The documentation is rather sparse about that topic. But that is absolutely a good idea. I wanted to tackle that when I have time / all other performance options are done (sounds like probably never.. :( ). I you have time it would be nice if you could look into that.

Another thing I considered is putting the functions into `FPATH` which is the building block for `autoload` -  also a very good idea.

Btw. It would be super helpful to have some sort of measuring script. Like calling a function 1000 times and showing stats for that. Sure the bare thing is not hard to do, but I'd like it to be more generic and put that in our debugging folder. So that anyone could easily measure performance for each segment (and core functions) on their machine. Probably with computing a baseline, so that we can compare the numbers..

**Comment by docwhat** [comment]
> So, realistically, I think P9k provides far more flexibility than anyone actually uses, and we are doing it at the expense of speed, which everyone actually cares about.

I think this is the critical bit.  Right now there is _way_ too much flexibility (both on-the-fly changing of values and knobs you can tweak on segments).

I'd rather have nearly zero on-the-fly changing and nearly no knobs for segments.

To counter the inconvenience of on-the-fly changing of values, have a way to regenerate segments, colors, whatever on-demand (versus the current automatic behavior).

To count the inconvenience of having few configuration knobs for segments, I would propose we make writing a segment nearly trivial.  This would let someone fork a segment to make it do what they want instead of keep piling on knobs.

If the segments could have been 100% forked in github then instead of modifying PL9K `status` segment directly, I could have forked it and added the pipestatus and signames in my fork.

It also means that very specialized segments (e.g. AWS and a potential [IBM Cloud](https://www.ibm.com/cloud/) segment I was thinking about) can be maintained outside the core PL9K source by people passionate about it.

**Comment by dritter** [comment]
> To count the inconvenience of having few configuration knobs for segments, I would propose we make writing a segment nearly trivial. This would let someone fork a segment to make it do what they want instead of keep piling on knobs.

Trivial _and_ flexible is hard to do both.. 😏 

> If the segments could have been 100% forked in github then instead of modifying PL9K status segment directly, I could have forked it and added the pipestatus and signames in my fork.

This would require a very stable API, which we don't have yet. And it would be harder to change the API, if we want to change it anyway. And updating/installing segments might be a pain (if the users were left alone). On the other hand, we would need to write a installation / update mechanism. I mean, I see P9K more a configuration Framework than a ZSH theme, but that would definitely make it a Framework..

**Comment by docwhat** [comment]
I was just musing out loud about trade offs

**Comment by onaforeignshore** [comment]
@robobenklein Your suggestion to [autoload](https://github.com/bhilburn/powerlevel9k/issues/817#issuecomment-404624441) segments would be problematic in the sense that segments have additional settings and/or functions that should be run only once on sourcing the file as well as a `prompt_xxx` function that gets called when building the prompt. Unfortunately, the settings of the prompt segment get lost during autoload.

**Comment by robobenklein** [comment]
@onaforeignshore That's an interesting find, I'll look into getting around that. Might start a basic scaffold of a prompt to try out weird new things.

**Comment by bhilburn** [comment]
Just as a general update here, the new codebase, v0.7.0, does lean more towards pre-initializing a lot of things to favor speed. I think we are all in agreement that less on-the-fly flexibility in favor of better performance is something that P9k will benefit from.

@dritter @onaforeignshore - Is there anything specific, on this topic, that we need to address in the `next` branch right now?

**Comment by robobenklein** [comment]
@bhilburn If possible, I'd like to ensure a few things are included on the 0.7 if possible.

A big point here is how compiling the sourced zsh files really makes a difference. With the p10k experiment I found that I reduced load time from `0.116` to `0.031`, or more on some machines, just by compiling files to their `*.zwc`s before sourcing. (This becomes more extreme on spinning drives and network-backed storage like at my school.)

Another change I'd appreciate is a reduction in the number of individual `P9K_` variables. I've found that using ZSH associative arrays for segments made a lot of sense since most of the options were just strings. Options could be set via `p9k_segment[some-option]="value"` and then filling `p9k_segment` assoc. array with the defaults would allow users to view those defaults like `echo ${(kvj.\n.)p9k_segment}`. These arrays are what I've been reading from during runtime, and the performance difference from using explicit `_SEGMENT_OPTION` variables wasn't noticeable. Even if not using arrays, setting the variables to their defaults so they can be seen would be helpful. (This could be addressed in the get_defaults.)

Also, @onaforeignshore I found that the autoload mechanism is actually working really well. I tried composing segments of multiple `prompt_<segment>_<function>` and autoloaded them as they are used/needed during the (runtime) prompt render. This also made extensibility really easy, since users could just define their own functions in the same way they were loaded from files.

**Comment by robobenklein** [comment]
For compiling, I did something like this:

```
function prompt_p10k_compile () {
  emulate -L zsh
  setopt extendedglob
  unsetopt autopushd
  local curdir="$PWD"
  cd ${_P10K_0[repo]}/p10k_functions
  for f in ./*; do
    [[ $f != *.zwc ]] && {
      echo "compiling $f ..."
      zcompile $f
    }
  done
  cd ../segments
  for f in ./*; do
    [[ $f != *.zwc ]] && {
      echo "compiling $f ..."
      zcompile $f
    }
  done
  cd $curdir
}
```
(probably can write one better than that)

You can spin that off async on startup with `cmd 2>&1 >/dev/null &` and then don't have to worry about it. I just had it as a command that was run `onpull` from zplugin.

If you don't want to spin that off every time, just compare one of the file timestamps (like a version indicator or .git folder to the .zwcs) before forking.

**Comment by bhilburn** [comment]
I am on a issue-cleaning spree. This issue hasn't had motion in quite some time, and so I am closing it out due to inactivity. If anyone would like to re-open it because they feel it is un-resolved and is something they care about, please feel free to re-raise the discussion!
