### ISSUE TITLE
Suggestion: smaller releases / Semantic Versioning

### ISSUE THREAD

**Issue by sambadevi** [bhilburn/powerlevel9k#822]
I would like to suggest smaller releases instead of waiting for the `next` branch.

There are PRs which could be merged without any problems, which would be worth a minor release on its own. Instead we are currently waiting until everything is finished in `next` (At least that’s what I saw the last few weeks).

We already have a versioning with major.minor.patch, however, when I look in the releases tab on github I see a few things which should’ve been a minor instead of just a patch, maybe we could use some automation and commit-convention here?

**Comment by dritter** [comment]
I had a discussion with @bhilburn about that in the [chat](https://gitter.im/bhilburn/powerlevel9k?at=570eb1ee4c2125fc3f02215c). His answer was [this](https://gitter.im/bhilburn/powerlevel9k?at=570eb27c5cd40114649b0853) and [this](https://gitter.im/bhilburn/powerlevel9k?at=570eb2942c9711166431a7ba).

I agree that semver is a great way of versioning software, and I'd love to use it in P9K. But we need a proper concept here, which should be textfile within the repo (something like `SEMVER.md`).
The paper should answer some questions:
- What is considered a BC break? 
-- Renaming of functions for sure, but renaming of variables?
-- And what about changing the signature of functions?
- What is defined as a public API (user facing)?
-- What are internal functions? Renaming these should not increment major.

Btw. [Good impression of semver](https://twitter.com/sebastiankugler/status/992310265902333952)

**Comment by bhilburn** [comment]
Thanks for opening this, @sambadevi! 

So, we actually *are* using SemVer - it just doesn't have any meaning right now because we are <1.0.0, which means we can basically do anything we want. Once we hit v1.0.0, anything that causes a config breakage or required change, for example, will be the equivalent of an "API change", etc.,

With regard to more regular releases, that would also be great. Frankly, the primary reason we aren't doing that right now is simply manpower. Fully testing the current state of `next` isn't completely automated right now, and making sure we are ready for a release takes a not inconsiderable amount of effort. Better automation (including more complete testing) would go a long way to making more regular releases possible.

It's worth noting that the new codebase, which will be in the v0.7.0 release, does have a lot of tests built out thanks to hard work from @dritter and @onaforeignshore. As we continue to expand this, it will make it possible for us to more regularly make tag releases with confidence.

I hope that helps! If you have any further thoughts, please don't hesitate to continue to comment here or in Gitter `=)`
