### ISSUE TITLE
Unexpected formatting in Intellij IDEA Terminal

### ISSUE THREAD

**Issue by Xerus2000** [bhilburn/powerlevel9k#831]
![](https://user-images.githubusercontent.com/13354331/39786371-965860ee-5320-11e8-8dde-bf3cd0ef57f3.png)
![](https://user-images.githubusercontent.com/13354331/39786374-9949994e-5320-11e8-89ee-07cac1882314.png)
As you can see, the command prompt starts at a new line even though it shouldn't. Furthermore, after typing the first command, all subsequent command prompts have a grey bar which is replaced while I type.
I am unsure whether this is an issue on Jetbrains' side or on yours.

**Comment by sambadevi** [comment]
Hi @Xerus2000, could you please add your p9k config?

Also, this could be a problem of IntelliJ, which OS are you using? And which terminal emulator are you using?

I remember IntellJ having a few problems with escape sequences on Windows with CMD (which is the default setting afaik)

**Comment by Xerus2000** [comment]
I am using the latest Intellij IDEA 2018.1.3 on Linux Mint. My config is the default except I removed the history from the right.

Afaik Idea emulates the Terminal itself, but I'm not too familiar with the background. Outside of Idea I use Konsole and it works great.

**Comment by diegorm90** [comment]
I'm having the same problem that @Xerus2000 with Intellij IDEA 2018.1.2 Ultimate Edition. I'm using the powerlevel9k default config on macOS High Sierra.
The problem seems to appear when there are "extra characters" in the git status at left (ie, files changed without commit, stash, files commited without push, etc)

**Comment by bhilburn** [comment]
@Xerus2000 @diegorm90 - I assume you are still seeing this issue? Unfortunately, I'm not super sure what to do about this. Since the problem doesn't happen anywhere except in IntelliJ, it seems like it's a font rendering problem with the IDE rather than P9k.

Thoughts from anyone else? Anything we can do, here?

**Comment by bhilburn** [comment]
Going to close this one out due to inactivity.

**Comment by Xerus2000** [comment]
To give an update:
It usually looks fine now:
![image](https://user-images.githubusercontent.com/13354331/50645386-bc850280-0f73-11e9-94a9-1f924a9b02f1.png)
However, when I execute "reset", it ends up in a very weird state where every single command takes a few lines and it limits itself to only a fraction of the width:
![image](https://user-images.githubusercontent.com/13354331/50645473-edfdce00-0f73-11e9-907f-9cb061dff7bb.png)
