### ISSUE TITLE
Multiline prompt with right prompt on first line and segments on second line

### ISSUE THREAD

**Issue by notrev** [bhilburn/powerlevel9k#840]
Hello!
I want to have a multiline prompt like this:
```
user@host > dir > vcs                                             status < time
background_jobs > #command input
```

I have tried many combinations using the following variables:

```
POWERLEVEL9K_PROMPT_ON_NEWLINE
POWERLEVEL9K_RPROMPT_ON_NEWLINE
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX
POWERLEVEL9K_PROMPT_ADD_NEWLINE
```

Using the `newline` segment on left prompt will move the right prompt one line down, and I don't want that

The closest I got to achieving what I want is:
```
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=" "
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(virtualenv context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
```
The problem is that I will have to copy/rewrite the segments functions into _.zshrc_ in order to call them inside `POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX`, as it apparently does not accept segments as `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` does.

My questions are:

1. Is there any way to use segments in the second line while keeping the right prompt in the first line?

2. Is it currently possible to define segments inside `POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX` without recreating the functions?

3. Do you plan to implement the feature on question 2?

Thanks in advance.

**Comment by bhilburn** [comment]
I am on a issue-cleaning spree. This issue hasn't had motion in quite some time, and so I am closing it out due to inactivity. If anyone would like to re-open it because they feel it is un-resolved and is something they care about, please feel free to re-raise the discussion!

**Comment by elder-cb** [comment]
Just came across this issue and PR while searching for this exact feature: having the right prompt on the first line while still having configurable segments on the prompt line.
My reason for this is that I like having the prompt on a new line so that the right prompt is not included if I want to copy and paste the command+output, but I'd like having at least the `root_indicator` segment on the prompt line because having it on the previous line might make it less visible :/

Any chance that PR can be updated (I see it has conflicts now) and merged? :)

**Comment by romkatv** [comment]
> Any chance that PR can be updated (I see it has conflicts now) and merged? :)

I wouldn't hold my breath. This project isn't very active.
