### ISSUE TITLE
Auto Refresh of POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX

### ISSUE THREAD

**Issue by cleveyeo** [bhilburn/powerlevel9k#850]
Hi all,
 
I am trying to make a customise prompt that reflects on my internet connectivity. However, it will refresh according to my internet connectivity if i add it into the standard left or right prompt. If i add it into the multiline_last_prompt_prefix, it will not get refresh or updated after i press the 'Enter' key.
Below is my code inside of .zshrc where i added the multiline_last_prompt,

```
#Settings for Powerlevel9K
POWERLEVEL9K_MODE="awesome-patched"

POWERLEVEL9K_PROMPT_ON_NEWLINE=true

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""

POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=$(prompt_connectivity left 1 && prompt_battery left 2 && left_prompt_end)
```

I will also like to ask how does the prompts get updated upon pressing of 'Enter' key for the left or right prompts. Thanks in advance. :)

**Comment by dritter** [comment]
Hi @cleveyeo !
Thanks for the report. I'll try to picture my workaround for this issue here. Note: `${SECONDS}` print the seconds since the shell was started.
```ZSH
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=${SECONDS}
```
This is our initial setup. 

1. Observation
`${SECONDS}` gets evaluated as soon as we type this command into the prompt. 
2. Observation
Everytime we retype this variable, we get the new value.

So we need a command that resets this variable before each command:
```ZSH
function resetP9kLastPromptPrefix() {
  POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=${SECONDS}
}
add-zsh-hook precmd resetP9kLastPromptPrefix
```
Now it should work as expected. :)

**Comment by bhilburn** [comment]
Closing this one out due to inactivity. Let us know if you still need assistance!

Thanks for the thorough user support here, @dritter !
