### ISSUE TITLE
Noticeable delay on macOS

### ISSUE THREAD

**Issue by alienxp03** [bhilburn/powerlevel9k#855]
Switching to `powerlevel9k` made my prompt to be noticeably slower than before. Is there any reason why?

`ys` theme
![original](https://user-images.githubusercontent.com/672704/40884849-f86e270a-674d-11e8-92d4-7ab7062f38ba.gif)

`powerlevel9k` theme
![jun-03-2018 16-48-00](https://user-images.githubusercontent.com/672704/40884856-0942bffa-674e-11e8-92b8-e404ad8218af.gif)

**Comment by dritter** [comment]
Hi @alienxp03 !
Thanks for the report. Yes, performance is a long pain point in P9K..
I'll try to explain the different types of bottlenecks and show what we are currently working on.

- Obvious things first: P9K has grown a lot in the last years. So there is a lot of code to execute.
- Some parts of that code is pretty IO intensive. So a fast SSD would help.
- Use of slow wrappers. Currently we execute the plain commands, without bypassing any aliases or wrappers. This may be a cause for lagginess, but is already addressed at some points (#797).
- Maximum flexibility: We lately had a discussion about that (#817) and started optimising for speed (#833)
- Avoid large git repos. At least keep them clean. A lot of untracked files will slow down the Prompt (https://github.com/bhilburn/powerlevel9k/issues/323#issuecomment-253315784)
- Use a recent version of git (especially on Mac; the shipped version of git is ancient)
- Use GNU/Coreutils on Mac instead of the shipped ones
- Make use of ZSHs async capabilities. We tried that in the past (#344) and are working on getting [ZSH-Async](https://github.com/mafredri/zsh-async/) integrated.

I hope this gives some insights about this topic and shows that we are trying to fix the performance issues.

**Comment by cameroncooke** [comment]
Mines twice as slow as the one in the preview above and I'm using minimal options and plugins. Was using Agnoster theme and it had the same Git capabilities and was much faster.

**Comment by bhilburn** [comment]
@alienxp03 @cameroncooke - The move to v0.7.0, especially once asynchronous segments are enabled, should go a long way, here.

We have a decent discussion going about exactly this topic over in #732, and I'm going to close this issue to keep the conversation focused in that issue. If you're up for trying out `next` and letting us know how it works for you over in #732, that would be great!
