### ISSUE TITLE
[SUPPORT] Add kube-ps1 prompt to left prompt segments

### ISSUE THREAD

**Issue by vielktus** [bhilburn/powerlevel9k#860]
Hi, 
I can use the segment `kubecontext` in left prompt. But no way to quickly on/off, so I want to change to `oh-my-zsh's plugin kube-ps1` [https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/kube-ps1](url). It has `kubeon` and `kubeoff` command to quickly on/off the string in the prompt.
I included this plugin like this in my `~/.zshrc`
```
plugins=(
  git
  virtualenv
  aws
  kube-ps1
)
```
I dont know what's the segment string to insert into left prompt segment. I tried `kube-ps1` but it doesn't work.
```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir virtualenv aws kube-ps1 vcs)
```
The error is:
```
build_left_prompt:12: command not found: prompt_kube-ps1
```

Is there a way to do this ?

**Comment by dritter** [comment]
Hi @vielktus ,

sorry for the late response. So that `kube-ps1` you are referring to is actually from [jonmosco/kube-ps1](https://github.com/jonmosco/kube-ps1). `kubeon`/`kubeoff` set a file that disables the prompt if it exists. It would be possible to do this with P9K internal means (like removing and adding `kubecontext` from left/right prompt elements).

Another way would be to do it with a [custom](https://github.com/bhilburn/powerlevel9k#custom_command) segment. Custom segments can output anything in a segment that echos a string. 
So, to get that in a segment you just need to set `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir virtualenv aws custom_kube_ps1 vcs)`.
Caveat: I did not test any of that, and it might look a bit off. Especially, because `kube-ps1` writes own fore- and background colors, that might interfere with our own. If that is the case, you could either change that custom segments background color to match the color of `kube-ps1`, or you need to find a method in the `kube-ps1` code that outputs the status string, without the colors.

Hope that helps.

**Comment by porcupie** [comment]
@vielktus  I didn't want to always display the kubecontext segment, so I forked and modified it slightly to only display the segment when `KUBECONFIG` environment variable is set or a default `~/.kube/config` file exists (I don't use that file on purpose). 

You may find the modification useful or as a starting point to customize your own:
* porcupie/powerlevel9k@769dbf915d579e6721526077a04a068f0a0377e4

**Comment by zikes** [comment]
@dritter I tested your idea and it worked so well that I'm thinking maybe the existing P9K `kubecontext` segment should be deprecated in favor of kube-ps1: https://gist.github.com/zikes/3179da36f3a87aee497398a6e9b88481
