### ISSUE TITLE
White "arrow" with 'clear' background color

### ISSUE THREAD

**Issue by lucatrv** [bhilburn/powerlevel9k#870]
I'm using Gnome Terminal with the standard Dark Tango theme. The background color of the terminal is not  completely black, so I can distinguish the pure black background color of the OK status mark.
I tried to set `POWERLEVEL9K_STATUS_OK_BACKGROUND='clear'`, but then I see a white "arrow" (triangle) by the OK status mark. The same happens for instance with `POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='clear'`.
Is it possible to set 'clear' background color without white "arrow"?
Thanks

**Comment by dritter** [comment]
Hi @lucatrv,
the easiest way to create the illusion of a transparent background is to set the background color to match your terminal color. This has to be done, because the "arrows" you see are the segment separators (or segment sub-separators) and they are printed in the foreground (backgrounds in ZSH can only be rectangular). The only segment, where you could use a transparent background (`BACKGROUND='none')  is the last left segment, as you could then set `POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=''`..

I hope that helps (if it does not, please post a screenshot).

**Comment by lucatrv** [comment]
```
POWERLEVEL9K_STATUS_OK_BACKGROUND='235'
```
did the trick.

Thanks for the hint, hopefully this is going to help others using Gnome Terminal.

**Comment by dritter** [comment]
Awesome! Have fun!
