### ISSUE TITLE
Help Wanted: Homebrew Package Maintainer

### ISSUE THREAD

**Issue by ryanwhocodes** [bhilburn/powerlevel9k#876]
I use Powerlevel9k on a mac and already use Homebrew for package management. Would you consider including Powerlevel9k in Homebrew?

**Comment by bhilburn** [comment]
@ryanwhocodes - This is a great idea, I think - especially since so many mac users are installing ZSH from homebrew, anyway. 

I don't have any experience writing homebrew packages, and I'm not sure that anyone else on our team does, either. If there is anyone in the community up for taking this on, let me know! This is for sure something I'd like to see done.

**Comment by dritter** [comment]
Awesome! Thanks @sambadevi

**Comment by bhilburn** [comment]
Agreed! Thanks so much, @sambadevi! And I see the Wiki has already been updated, too =)
