### ISSUE TITLE
Changing Terminal Size Causes Erratic Prompt Behavior

### ISSUE THREAD

**Issue by colbymorrison** [bhilburn/powerlevel9k#881]
When I change the size of the terminal the prompts go like this:
![recording 1](https://user-images.githubusercontent.com/20446774/41754190-65349a18-759f-11e8-8524-92495d8a1364.gif)

Using iTerm2 with OhMyZsh

**Comment by warpedgeoid** [comment]
I do not see this in iTerm2 (3.1.6) on OS X 10.13.5. I do, however, have an issue where upon reducing the window size and then increasing it again, the spacing between subsequent prompts in the scroll history increases by one line.

**Comment by V1a9** [comment]
Having the same issue in tilix terminal v 1.8.1 with OhMyZsh on elementary OS loki.

**Comment by xufab** [comment]
Same issue with Terminator

**Comment by bhilburn** [comment]
So, unfortunately, this really isn't something P9k can fix. This is due to how your terminal emulator is triggering re-draws of the prompt, and different emulators handle it differently. This is why you don't see this problem on iTerm2 when you resize in one direction, but it does appear when you do it twice, etc.,

Sorry, all, but this is a terminal thing, not a P9k thing! :(

**Comment by danielkroon** [comment]
@colbymorrison did you already found a way to fix this? I found out that using ctrl + l fixes the screen. But I don't want to do that every time I'm resizing my window.

**Comment by romkatv** [comment]
@danielkroon This can be fixed only by changing zsh itself. See [this issue](https://github.com/romkatv/powerlevel10k/issues/175) for details.
