### ISSUE TITLE
'Status' positioning error. Wrong line.

### ISSUE THREAD

**Issue by kirVershinin** [bhilburn/powerlevel9k#909]
Hi, 
My problem is simple i hope. I guess status icon in a wrong place. I would like to see status icon parallel to the wrong command. How i can do this?

[Screenshot](https://imgur.com/wdLvGCI)

My .zshrc

```
POWERLEVEL9K_MODE='nerdfont-complete'

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status)
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_VCS_GIT_ICON='\uE1AA'
POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\uE1AA'
```

**Comment by zikes** [comment]
Positions are relative to the prompt, which will typically start on a new line following any command unless that command fails to end in a newline. That means that in order to get the prompt on the same line as the command, it would need to be moved backwards, or up a line. Technically this is possible on some terminals, according to this StackOverflow answer: https://stackoverflow.com/a/4873071

You would need to print the `\e[A` character before the right prompt, but that seems to break P9K in a few ways. I threw together this quick custom segment to test it out:
```
zsh_back_line(){
  printf '\e[A'
}
POWERLEVEL9K_CUSTOM_BACK_LINE='zsh_back_line'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(custom_back_line status go_version time)
```
And the results, well... :grimacing: 
![screenshot from 2018-07-13 20-16-05](https://user-images.githubusercontent.com/410905/42719357-e16130f6-86d9-11e8-8555-375bd06e79ce.png)

**Comment by onaforeignshore** [comment]
Technically, this would you require to move up **and** down, but the problem is that there is no way to know how big the output is between command lines, so it could be 2 lines or 200...
