### ISSUE TITLE
Username color identical to root's since 264897a

### ISSUE THREAD

**Issue by jadoro** [bhilburn/powerlevel9k#913]
Hi,

after routinely updating my checkout, I've noticed the following unexpected behavior:

* Before commit 264897a, the user- and hostname was rendered with a different color depending on whether the user was root or not.
* After commit 264897a, user- and hostnames are always rendered yellow.

I'm not sure if this change in behavior is intended, since it disables a valuable feature I'd rather expect it to be a regression.

Thanks a lot for your great work!

**Comment by robobenklein** [comment]
See #898 ?

**Comment by Suspicat** [comment]
I checked, to see if I was having this because of sudo, but it is "CONTEXT_DEFAULT" (I can change the color for that from yellow to something else).
The version I am using is the git master branch cloned into the oh-my-zsh folder to use the theme.
I guess a temporary workaround would be to set something else than yellow for POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND

**Comment by jadoro** [comment]
Sorry for that late reply.
@Suspicat's fix worked for me, thanks a lot!
