### ISSUE TITLE
Change prompt user name and host name

### ISSUE THREAD

**Issue by ishanSrt** [bhilburn/powerlevel9k#914]
I use `zsh` and `powerlevel9k` and my `$USER` is set to a `very_large_name` and my host name is set to `very_large_name'sMacbookPro` and when I get the prompt `very_large_name@very_large_name'sMacbookPro` infront of every line its awkward and takes up a lot of space. Is there a way I can change these display values to something short? Setting these variables in `.zshrc` doesn't yield the results although I was able to completely disable them using DEFAULT_USER=$USER or by removing `context` from `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` but how can I change this to some suitable value I desire like my condensed username. I suppose I can do it my editing the `PROMPT` variable in the `.zsh.theme` file. Can some one guide me how exactly would I be able to do it?

**Comment by onaforeignshore** [comment]
You need to set `POWERLEVEL9K_CONTEXT_TEMPLATE` to what you require. This is achieved with zsh end truncation - `%x>r>%v` where `x` is the number of characters, `r` is the replacement character(s) and `v` is the zsh prompt variable you want to use.

In our case, we want to shorten the username `%n` and the hostname `%m`. This can be achieved with `"%5>...>%n%>>@%10>...>%m"`. This will shorten the username to 5 characters including the replacement character(s), so `Chris` would stay the same, but `Christopher` would become `Ch...`. The same for the hostname for a length of 10 characters. The `%>>` in the middle of the string 'resets' the truncation otherwise the first truncation would apply to the whole string.

So, the line you need to add to your `.zshrc` would be:
```zsh
POWERLEVEL9K_CONTEXT_TEMPLATE="%5>...>%n%>>@%10>...>%m"
```

I hope this helps you get what you desire.

**Comment by onaforeignshore** [comment]
You can also opt to use the `user` and `host` segments separately instead of `context`, in which case you would set
```zsh
POWERLEVEL9K_HOST_TEMPLATE="%10>...>%m"
POWERLEVEL9K_USER_TEMPLATE="%5>...>%n"
```

**Comment by ishanSrt** [comment]
Thanks a lot @onaforeignshore that works.

**Comment by bhilburn** [comment]
Glad you're up and running, @ishanSrt, and thanks so much for providing great support, @onaforeignshore!

**Comment by gaborod16** [comment]
Hello @onaforeignshore and thanks for your help to @ishanSrt previously.
I had a similar problem. Your solution helped me to get started but I had to develop a bit more on it.

`POWERLEVEL9K_CONTEXT_TEMPLATE="%4>>%n%>>@%7>>%m%>>"`

I had to add
`%>>` to the end of the template so the rest of it doesn't get truncated and the machine name truncation works properly.

Hope this helps anyone in the future.

**Comment by ishanSrt** [comment]
Oh that works too!
