### ISSUE TITLE
Question/Issue: HEX Color for p9k / pywal support

### ISSUE THREAD

**Issue by sambadevi** [bhilburn/powerlevel9k#963]
I am trying to integrate p9k into my pywal theme, however, pywal generates either escape codes or hex codes for color settings.

I tried using `POWERLEVEL9K_OS_ICON_FOREGROUND="$($color1)"` after generating a wal color scheme, but all I get when sourcing my .zshrc is `getColor:12: command not found: #692F8E`

#### Environment Information
- zsh 5.5.1 (x86_64-apple-darwin17.5.0)
- antigen
- p9k is installed from master branch (`antigen theme bhilburn/powerlevel9k powerlevel9k`)
- iterm2

**Comment by onaforeignshore** [comment]
Powerlevel9k makes use of Z Shell's `%F{x}` and `%f` for foreground and `%K{x}` and `%k` for background colours. We don't use the escape codes that are required for what you are attempting to do.

**Comment by onaforeignshore** [comment]
@bhilburn Can we close this issue as there is no further activity?

**Comment by RantSomeWhere** [comment]
Necro-bumping this issue because I have the same wish. I can't, for the life of me, find a theme as cool as this one with pywal support. Because the color options are limited to color codes, colors are always slightly off from my usual colorscheme. Is it possible to add hex color support to p9k? Or would that require a major rewrite? @bhilburn

**Comment by onaforeignshore** [comment]
This would require a major rewrite since the generators use the `%F`, `%f`, `%K`, and `%k` codes (for 256 colors and hex color support would require using ASCII escape codes.
