### ISSUE TITLE
10 second delay between zsh prompt displays after command completes(yes TEN)

### ISSUE THREAD

**Issue by fryjustinc** [bhilburn/powerlevel9k#964]
I didn't believe that powerlevel 9k could really be what is causing this but after individually commenting out every single line in my zshrc, totally replacing my zplug install, and switching my powerlevel9k config to default, the only thing that fixed the crazy lag in between prompts was commenting out powerlvl9k loading in my .zshrc (remember this is with DEFAULT config too). I posted a picture for your amusement at my suffering. (check out the timestamps on the right) I definitely could use some help disecting this one. (and no my home dir isn't tracked but I do have about 300 or so tracked projects throughout my drive, although they're not in path. 
![screen shot 2018-08-21 at 4 24 42 am](https://user-images.githubusercontent.com/6653944/44393742-1de39200-a4fb-11e8-85a2-28e1890ae83b.jpg)

**Comment by truongnmt** [comment]
Yes, I'm suffering from the same behavior. Seem that it's so bloated.

**Comment by crsantos** [comment]
Same here, unfortunately. 
Not sure if it's prezto's fault... but I started feeling this delay when I pulled 600 commits from powerlevel9k's master branch.
Happy to help debugging this.

**Comment by bhilburn** [comment]
@fryjustinc - Thank you so much for taking the time to deep-dive on this and look at things further! I really do appreciate you investigating things and providing insight & suggestions :)

1. Regarding `sudo -n true`, try pulling `master` and having another look. This behavior actually just changed with the merge of #937 a couple of days ago. That said, `id -un` might still be the better option? Setting a default user probably isn't a bad idea, either, actually - I'm surprised it's taken this long for someone to suggest that. Something as simple as `p9kuser` would go a long way to simplifying some conditionals.

2. You're right - `rbenv` is a rather expensive command, and probably one that doesn't need to be in the default segment list.

3. Yes, that color comparison is a sore point for p9k, for sure. It's unfortunately not as easy as just parsing them on init, because many segments change their colors depending on segment status. Can you think of a way to more efficiently do this for a dynamically colored prompt?

4. I'm always loathe to bring in additional dependencies, although I would very seriously consider it if it would speed up the `vcs` segment; `git`, especially, can be horribly slow. I am a little wary about `vcprompt`, though, as it looks like it was abandoned 4 years ago. I will happily consider any suggestions you have in this space, though! Especially in large `git` repositories, the `vcs` segment can slow to crawl, and not withstanding asynchronous segment drawing (coming in v0.7.0), we haven't found a good way to speed it up.

PRs would be fantastic! If you want to submit PRs for the items in #1, that would be excellent! I'll handle #2 myself. What are your thoughts on #3 and #4? Also, would be good to get @dritter's and @onaforeignshore's thoughts, here.

**Comment by fryjustinc** [comment]
@bhilburn ill put in a quick pull request for #1 later today. What I'm probably going to do is simply switch all the `sudo -n true` instances with `id -un` and an equality test against `sudo`it also would provide the username too so that would eliminate a later test. glad to hear 2 is taken care of. 3, I can definitely think of a few solutions but most of them would involve some kind of pseudo compilation step in between configuration and actually running the theme. There are data structures that would speed it up if you didn't want to do that though. 4, I would rewrite vcprompt myself. It's not that large. If you have the time, do you have a way I could reach out to you, or the other two individuals you mentioned if appropriate, to ask a few questions about functionality requirements and what exactly some of these steps doing (im thinking of the color stage). If not, that's no big deal either.

**Comment by bhilburn** [comment]
@fryjustinc - Yeah, compilation isn't really a good option for us unless it's auto-invoked by p9k and the dependencies are exceedingly simple. More efficient data structures would be excellent, though.

The codebase is about to undergo a titanic shift (i.e., a shift to a complete rewrite, that's already waiting & ready to go). Chatting on the phone or by VC would be great. Feel free to email me (bhilburn gmail) and we can go from there =)

**Comment by onaforeignshore** [comment]
1. Already done
2. Already done
3. Implemented in `next`
4. After some research, it turns out this test is redundant so I am removing it in the VCS PR I am working on.

**Comment by dritter** [comment]
Hey @fryjustinc ,

I just wanted to drop by and ask you if you could check our `next` branch, cause we did some massive performance improvements there. Thx.

**Comment by fryjustinc** [comment]
Hi Dominik,

I'll take a look at the branch. Thanks!

**Comment by bhilburn** [comment]
@fryjustinc - Thanks! Please let us know what you find with the VCS performance on `next`, and any ideas you have for further improving it!

**Comment by romkatv** [comment]
@fryjustinc If you are still using Powerlevel9k, could you check if performance issues can be reproduced with [Powerlevel10k](https://github.com/romkatv/powerlevel10k/#for-powerlevel9k-users)?

**Comment by bhilburn** [comment]
I am on a issue-cleaning spree. This issue hasn't had motion in quite some time, and so I am closing it out due to inactivity. If anyone would like to re-open it because they feel it is un-resolved and is something they care about, please feel free to re-raise the discussion!
