### ISSUE TITLE
os_icon is not rendered

### ISSUE THREAD

**Issue by Goron1606** [bhilburn/powerlevel9k#987]
I recently installed P9k with oh-my-zsh. I was setting up 2 machines in parallel.
However the below line does not render the Linux icon but the other machine renders. I have followed all the steps mentioned in installation.

`POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status os_icon battery context dir vcs)`

I have uploaded the screen shot [here](https://ibb.co/bJjCkU)

When I do `source ~/.zshrc` It solves the issue. This occurs only when I open the terminal

Am using
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
framework - Oh-My-ZSH
Installed P9k by cloning the repo
Using Gnome terminal

**Comment by onaforeignshore** [comment]
do you have all the settings before you source p9k?

**Comment by Goron1606** [comment]
Yes I do..

**Comment by rjorgenson** [comment]
This was fixed in the most recent version(0.6.6) - At one point they added code points for all the different flavors for the nerdfont and fontconfig configurations but when ported to awesome-patched which doesn't have those fonts they put text in rather than the more generic icons that are included in the awesome fonts. Updating your p9k should fix this issue.

**Comment by Goron1606** [comment]
I'm indeed using the latest version 0.6.6

**Comment by dritter** [comment]
Glad you got it working.

Thx @onaforeignshore and @rjorgenson for providing help.
